//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.wsat.controller.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.bradseg.cpat.integracao.model.vo.ArrayOfVigenciaBean;

@WebService(name = "BolAcessorioServicePortType", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br")
@XmlSeeAlso({
    br.com.bradseg.paol.wsat.controller.services.ObjectFactory.class,
    br.com.bradseg.cpat.integracao.model.vo.ObjectFactory.class
})
public interface BolAcessorioServicePortType {


    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns br.com.bradseg.cpat.integracao.model.vo.ArrayOfVigenciaBean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br")
    @RequestWrapper(localName = "listaDispositivoAntifurto", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br", className = "br.com.bradseg.paol.wsat.controller.services.ListaDispositivoAntifurto")
    @ResponseWrapper(localName = "listaDispositivoAntifurtoResponse", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br", className = "br.com.bradseg.paol.wsat.controller.services.ListaDispositivoAntifurtoResponse")
    public ArrayOfVigenciaBean listaDispositivoAntifurto(
        @WebParam(name = "usuario", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br")
        String senha);

}
