//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.wsat.controller.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "BolAcessorioService", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br", wsdlLocation = "file:/C:/Projetos/workspace/WebServiceCalculo/src/BolAcessorioService.wsdl")
public class BolAcessorioService
    extends Service
{

    private final static URL BOLACESSORIOSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projetos/workspace/WebServiceCalculo/src/BolAcessorioService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BOLACESSORIOSERVICE_WSDL_LOCATION = url;
    }

    public BolAcessorioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BolAcessorioService() {
        super(BOLACESSORIOSERVICE_WSDL_LOCATION, new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolAcessorioService"));
    }

    /**
     * 
     * @return
     *     returns BolAcessorioServicePortType
     */
    @WebEndpoint(name = "BolAcessorioServiceHttpPort")
    public BolAcessorioServicePortType getBolAcessorioServiceHttpPort() {
        return (BolAcessorioServicePortType)super.getPort(new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolAcessorioServiceHttpPort"), BolAcessorioServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BolAcessorioServicePortType
     */
    @WebEndpoint(name = "BolAcessorioServiceHttpPort")
    public BolAcessorioServicePortType getBolAcessorioServiceHttpPort(WebServiceFeature... features) {
        return (BolAcessorioServicePortType)super.getPort(new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolAcessorioServiceHttpPort"), BolAcessorioServicePortType.class, features);
    }

}
