//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.wsat.controller.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "BolCotacaoAuto", targetNamespace = "http://services.controller.wsat.paol.bradseg.com.br", wsdlLocation = "file:/C:/Projetos/workspace/WebServiceCalculo/src/BolCotacaoAuto.wsdl")
public class BolCotacaoAuto
    extends Service
{

    private final static URL BOLCOTACAOAUTO_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projetos/workspace/WebServiceCalculo/src/BolCotacaoAuto.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BOLCOTACAOAUTO_WSDL_LOCATION = url;
    }

    public BolCotacaoAuto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BolCotacaoAuto() {
        super(BOLCOTACAOAUTO_WSDL_LOCATION, new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolCotacaoAuto"));
    }

    /**
     * 
     * @return
     *     returns BolCotacaoAutoPortType
     */
    @WebEndpoint(name = "BolCotacaoAutoHttpPort")
    public BolCotacaoAutoPortType getBolCotacaoAutoHttpPort() {
        return (BolCotacaoAutoPortType)super.getPort(new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolCotacaoAutoHttpPort"), BolCotacaoAutoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BolCotacaoAutoPortType
     */
    @WebEndpoint(name = "BolCotacaoAutoHttpPort")
    public BolCotacaoAutoPortType getBolCotacaoAutoHttpPort(WebServiceFeature... features) {
        return (BolCotacaoAutoPortType)super.getPort(new QName("http://services.controller.wsat.paol.bradseg.com.br", "BolCotacaoAutoHttpPort"), BolCotacaoAutoPortType.class, features);
    }

}
