//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.wsat.controller.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.bradseg.paol.wsat.controller.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.bradseg.paol.wsat.controller.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GerenciadorCalculoResponse }
     * 
     */
    public GerenciadorCalculoResponse createGerenciadorCalculoResponse() {
        return new GerenciadorCalculoResponse();
    }

    /**
     * Create an instance of {@link GerenciadorCalculo }
     * 
     */
    public GerenciadorCalculo createGerenciadorCalculo() {
        return new GerenciadorCalculo();
    }

    /**
     * Create an instance of {@link CalcularSeguroEndosso }
     * 
     */
    public CalcularSeguroEndosso createCalcularSeguroEndosso() {
        return new CalcularSeguroEndosso();
    }

    /**
     * Create an instance of {@link CalcularSeguroEndossoResponse }
     * 
     */
    public CalcularSeguroEndossoResponse createCalcularSeguroEndossoResponse() {
        return new CalcularSeguroEndossoResponse();
    }

}
