//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcessorioImpressaoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcessorioImpressaoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdAcessorio" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dsAcessorio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vlAcessorio" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcessorioImpressaoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdAcessorio",
    "dsAcessorio",
    "vlAcessorio"
})
public class AcessorioImpressaoVo {

    protected Integer cdAcessorio;
    protected String dsAcessorio;
    protected Double vlAcessorio;

    /**
     * Gets the value of the cdAcessorio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdAcessorio() {
        return cdAcessorio;
    }

    /**
     * Sets the value of the cdAcessorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdAcessorio(Integer value) {
        this.cdAcessorio = value;
    }

    /**
     * Gets the value of the dsAcessorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsAcessorio() {
        return dsAcessorio;
    }

    /**
     * Sets the value of the dsAcessorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsAcessorio(String value) {
        this.dsAcessorio = value;
    }

    /**
     * Gets the value of the vlAcessorio property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlAcessorio() {
        return vlAcessorio;
    }

    /**
     * Sets the value of the vlAcessorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlAcessorio(Double value) {
        this.vlAcessorio = value;
    }

}
