//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApoliceVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApoliceVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdAgenciaCobranca" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdAgenciaDebito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdAgenciaProdutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="cdAngariador" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="cdApolice" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdBancoCobranca" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdBancoDebito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdBandeiraCartaoCredito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdCindMesaNegocio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdConcessionaria" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="cdContaDebito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdContexto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdEmpresa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdInspetoria" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdItem" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdModalidade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdProdutoCliente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRegiao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRelacaoSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRevenda" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="cdSegurancaCartaoCredito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdSucursal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPagtoCarne" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaSegurado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoSistema" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdVendedor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cnroContrato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="coberturaApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}CoberturaApoliceVo" minOccurs="0"/>
 *         &lt;element name="dsDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtBaseCalculo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtEmissao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtFinalVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtLeasing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtProcessamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtValidadeCartaoCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flAceitacaoRestrita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flAutoResidencial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flImprimeCCB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flIndiceOCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flNovaTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flReterDevolucao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flTeleEmpresaFatura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listaClausulaApolice" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfClausulaApoliceVo" minOccurs="0"/>
 *         &lt;element name="mensagemErroVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}MensagemErroVo" minOccurs="0"/>
 *         &lt;element name="nmOrgaoEmissor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuCEP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCartaoCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuControleLeasing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuDiaVencimento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDigitoAgenciaDebito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDigitoContaDebito" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagamentoApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PagamentoApoliceVo" minOccurs="0"/>
 *         &lt;element name="parametroApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ParametroApoliceVo" minOccurs="0"/>
 *         &lt;element name="pcComissaoAPP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoRCF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoApp" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoOnline" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoPromocional" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoRcf" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcFatorAgravo" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="perfilApolicePropVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PerfilApoliceVo" minOccurs="0"/>
 *         &lt;element name="perfilApoliceSegVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PerfilApoliceVo" minOccurs="0"/>
 *         &lt;element name="pessoaApolicePropVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PessoaApoliceVo" minOccurs="0"/>
 *         &lt;element name="pessoaApoliceSegVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PessoaApoliceVo" minOccurs="0"/>
 *         &lt;element name="renovacaoApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}RenovacaoApoliceVo" minOccurs="0"/>
 *         &lt;element name="teleEmpresaApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}TeleEmpresaApoliceVo" minOccurs="0"/>
 *         &lt;element name="veiculoApoliceVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}VeiculoApoliceVo" minOccurs="0"/>
 *         &lt;element name="vlCustoApolice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApoliceVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdAgenciaCobranca",
    "cdAgenciaDebito",
    "cdAgenciaProdutor",
    "cdAngariador",
    "cdApolice",
    "cdBancoCobranca",
    "cdBancoDebito",
    "cdBandeiraCartaoCredito",
    "cdCindMesaNegocio",
    "cdConcessionaria",
    "cdContaDebito",
    "cdContexto",
    "cdEmpresa",
    "cdInspetoria",
    "cdItem",
    "cdModalidade",
    "cdProdutoCliente",
    "cdRegiao",
    "cdRelacaoSeguradoProprietario",
    "cdRevenda",
    "cdSegurancaCartaoCredito",
    "cdSucursal",
    "cdTipoPagtoCarne",
    "cdTipoPessoaProprietario",
    "cdTipoPessoaSegurado",
    "cdTipoSistema",
    "cdVendedor",
    "cnroContrato",
    "coberturaApoliceVo",
    "dsDocumento",
    "dsEmail",
    "dtBaseCalculo",
    "dtEmissao",
    "dtFinalVigencia",
    "dtInicioVigencia",
    "dtLeasing",
    "dtProcessamento",
    "dtValidadeCartaoCredito",
    "flAceitacaoRestrita",
    "flAutoResidencial",
    "flImprimeCCB",
    "flIndiceOCT",
    "flNovaTarifa",
    "flReterDevolucao",
    "flTeleEmpresaFatura",
    "listaClausulaApolice",
    "mensagemErroVo",
    "nmOrgaoEmissor",
    "nuBonus",
    "nuCEP",
    "nuCartaoCredito",
    "nuControleLeasing",
    "nuDiaVencimento",
    "nuDigitoAgenciaDebito",
    "nuDigitoContaDebito",
    "nuDocumento",
    "pagamentoApoliceVo",
    "parametroApoliceVo",
    "pcComissaoAPP",
    "pcComissaoAuto",
    "pcComissaoRCF",
    "pcDescontoApp",
    "pcDescontoAuto",
    "pcDescontoOnline",
    "pcDescontoPromocional",
    "pcDescontoRcf",
    "pcFatorAgravo",
    "perfilApolicePropVo",
    "perfilApoliceSegVo",
    "pessoaApolicePropVo",
    "pessoaApoliceSegVo",
    "renovacaoApoliceVo",
    "teleEmpresaApoliceVo",
    "veiculoApoliceVo",
    "vlCustoApolice"
})
public class ApoliceVo {

    protected Integer cdAgenciaCobranca;
    protected Integer cdAgenciaDebito;
    protected Long cdAgenciaProdutor;
    protected Long cdAngariador;
    protected Integer cdApolice;
    protected Integer cdBancoCobranca;
    protected Integer cdBancoDebito;
    protected Integer cdBandeiraCartaoCredito;
    protected String cdCindMesaNegocio;
    protected Long cdConcessionaria;
    protected Integer cdContaDebito;
    protected String cdContexto;
    protected Integer cdEmpresa;
    protected Integer cdInspetoria;
    protected Integer cdItem;
    protected String cdModalidade;
    protected Integer cdProdutoCliente;
    protected Integer cdRegiao;
    protected Integer cdRelacaoSeguradoProprietario;
    protected Long cdRevenda;
    protected Integer cdSegurancaCartaoCredito;
    protected Integer cdSucursal;
    protected Integer cdTipoPagtoCarne;
    protected String cdTipoPessoaProprietario;
    protected String cdTipoPessoaSegurado;
    protected Integer cdTipoSistema;
    protected Integer cdVendedor;
    protected String cnroContrato;
    protected CoberturaApoliceVo coberturaApoliceVo;
    protected String dsDocumento;
    protected String dsEmail;
    protected String dtBaseCalculo;
    protected String dtEmissao;
    protected String dtFinalVigencia;
    protected String dtInicioVigencia;
    protected String dtLeasing;
    protected String dtProcessamento;
    protected String dtValidadeCartaoCredito;
    protected String flAceitacaoRestrita;
    protected String flAutoResidencial;
    protected String flImprimeCCB;
    protected String flIndiceOCT;
    protected String flNovaTarifa;
    protected String flReterDevolucao;
    protected String flTeleEmpresaFatura;
    protected ArrayOfClausulaApoliceVo listaClausulaApolice;
    protected MensagemErroVo mensagemErroVo;
    protected String nmOrgaoEmissor;
    protected Integer nuBonus;
    protected String nuCEP;
    protected String nuCartaoCredito;
    protected String nuControleLeasing;
    protected Integer nuDiaVencimento;
    protected Integer nuDigitoAgenciaDebito;
    protected Integer nuDigitoContaDebito;
    protected String nuDocumento;
    protected PagamentoApoliceVo pagamentoApoliceVo;
    protected ParametroApoliceVo parametroApoliceVo;
    protected Double pcComissaoAPP;
    protected Double pcComissaoAuto;
    protected Double pcComissaoRCF;
    protected Double pcDescontoApp;
    protected Double pcDescontoAuto;
    protected Double pcDescontoOnline;
    protected Double pcDescontoPromocional;
    protected Double pcDescontoRcf;
    protected Double pcFatorAgravo;
    protected PerfilApoliceVo perfilApolicePropVo;
    protected PerfilApoliceVo perfilApoliceSegVo;
    protected PessoaApoliceVo pessoaApolicePropVo;
    protected PessoaApoliceVo pessoaApoliceSegVo;
    protected RenovacaoApoliceVo renovacaoApoliceVo;
    protected TeleEmpresaApoliceVo teleEmpresaApoliceVo;
    protected VeiculoApoliceVo veiculoApoliceVo;
    protected Double vlCustoApolice;

    /**
     * Gets the value of the cdAgenciaCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdAgenciaCobranca() {
        return cdAgenciaCobranca;
    }

    /**
     * Sets the value of the cdAgenciaCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdAgenciaCobranca(Integer value) {
        this.cdAgenciaCobranca = value;
    }

    /**
     * Gets the value of the cdAgenciaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdAgenciaDebito() {
        return cdAgenciaDebito;
    }

    /**
     * Sets the value of the cdAgenciaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdAgenciaDebito(Integer value) {
        this.cdAgenciaDebito = value;
    }

    /**
     * Gets the value of the cdAgenciaProdutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdAgenciaProdutor() {
        return cdAgenciaProdutor;
    }

    /**
     * Sets the value of the cdAgenciaProdutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdAgenciaProdutor(Long value) {
        this.cdAgenciaProdutor = value;
    }

    /**
     * Gets the value of the cdAngariador property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdAngariador() {
        return cdAngariador;
    }

    /**
     * Sets the value of the cdAngariador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdAngariador(Long value) {
        this.cdAngariador = value;
    }

    /**
     * Gets the value of the cdApolice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdApolice() {
        return cdApolice;
    }

    /**
     * Sets the value of the cdApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdApolice(Integer value) {
        this.cdApolice = value;
    }

    /**
     * Gets the value of the cdBancoCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdBancoCobranca() {
        return cdBancoCobranca;
    }

    /**
     * Sets the value of the cdBancoCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdBancoCobranca(Integer value) {
        this.cdBancoCobranca = value;
    }

    /**
     * Gets the value of the cdBancoDebito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdBancoDebito() {
        return cdBancoDebito;
    }

    /**
     * Sets the value of the cdBancoDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdBancoDebito(Integer value) {
        this.cdBancoDebito = value;
    }

    /**
     * Gets the value of the cdBandeiraCartaoCredito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdBandeiraCartaoCredito() {
        return cdBandeiraCartaoCredito;
    }

    /**
     * Sets the value of the cdBandeiraCartaoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdBandeiraCartaoCredito(Integer value) {
        this.cdBandeiraCartaoCredito = value;
    }

    /**
     * Gets the value of the cdCindMesaNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdCindMesaNegocio() {
        return cdCindMesaNegocio;
    }

    /**
     * Sets the value of the cdCindMesaNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdCindMesaNegocio(String value) {
        this.cdCindMesaNegocio = value;
    }

    /**
     * Gets the value of the cdConcessionaria property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdConcessionaria() {
        return cdConcessionaria;
    }

    /**
     * Sets the value of the cdConcessionaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdConcessionaria(Long value) {
        this.cdConcessionaria = value;
    }

    /**
     * Gets the value of the cdContaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdContaDebito() {
        return cdContaDebito;
    }

    /**
     * Sets the value of the cdContaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdContaDebito(Integer value) {
        this.cdContaDebito = value;
    }

    /**
     * Gets the value of the cdContexto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdContexto() {
        return cdContexto;
    }

    /**
     * Sets the value of the cdContexto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdContexto(String value) {
        this.cdContexto = value;
    }

    /**
     * Gets the value of the cdEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEmpresa() {
        return cdEmpresa;
    }

    /**
     * Sets the value of the cdEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEmpresa(Integer value) {
        this.cdEmpresa = value;
    }

    /**
     * Gets the value of the cdInspetoria property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdInspetoria() {
        return cdInspetoria;
    }

    /**
     * Sets the value of the cdInspetoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdInspetoria(Integer value) {
        this.cdInspetoria = value;
    }

    /**
     * Gets the value of the cdItem property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdItem() {
        return cdItem;
    }

    /**
     * Sets the value of the cdItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdItem(Integer value) {
        this.cdItem = value;
    }

    /**
     * Gets the value of the cdModalidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdModalidade() {
        return cdModalidade;
    }

    /**
     * Sets the value of the cdModalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdModalidade(String value) {
        this.cdModalidade = value;
    }

    /**
     * Gets the value of the cdProdutoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdProdutoCliente() {
        return cdProdutoCliente;
    }

    /**
     * Sets the value of the cdProdutoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdProdutoCliente(Integer value) {
        this.cdProdutoCliente = value;
    }

    /**
     * Gets the value of the cdRegiao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRegiao() {
        return cdRegiao;
    }

    /**
     * Sets the value of the cdRegiao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRegiao(Integer value) {
        this.cdRegiao = value;
    }

    /**
     * Gets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRelacaoSeguradoProprietario() {
        return cdRelacaoSeguradoProprietario;
    }

    /**
     * Sets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRelacaoSeguradoProprietario(Integer value) {
        this.cdRelacaoSeguradoProprietario = value;
    }

    /**
     * Gets the value of the cdRevenda property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdRevenda() {
        return cdRevenda;
    }

    /**
     * Sets the value of the cdRevenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdRevenda(Long value) {
        this.cdRevenda = value;
    }

    /**
     * Gets the value of the cdSegurancaCartaoCredito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdSegurancaCartaoCredito() {
        return cdSegurancaCartaoCredito;
    }

    /**
     * Sets the value of the cdSegurancaCartaoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdSegurancaCartaoCredito(Integer value) {
        this.cdSegurancaCartaoCredito = value;
    }

    /**
     * Gets the value of the cdSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdSucursal() {
        return cdSucursal;
    }

    /**
     * Sets the value of the cdSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdSucursal(Integer value) {
        this.cdSucursal = value;
    }

    /**
     * Gets the value of the cdTipoPagtoCarne property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoPagtoCarne() {
        return cdTipoPagtoCarne;
    }

    /**
     * Sets the value of the cdTipoPagtoCarne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoPagtoCarne(Integer value) {
        this.cdTipoPagtoCarne = value;
    }

    /**
     * Gets the value of the cdTipoPessoaProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaProprietario() {
        return cdTipoPessoaProprietario;
    }

    /**
     * Sets the value of the cdTipoPessoaProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaProprietario(String value) {
        this.cdTipoPessoaProprietario = value;
    }

    /**
     * Gets the value of the cdTipoPessoaSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaSegurado() {
        return cdTipoPessoaSegurado;
    }

    /**
     * Sets the value of the cdTipoPessoaSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaSegurado(String value) {
        this.cdTipoPessoaSegurado = value;
    }

    /**
     * Gets the value of the cdTipoSistema property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoSistema() {
        return cdTipoSistema;
    }

    /**
     * Sets the value of the cdTipoSistema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoSistema(Integer value) {
        this.cdTipoSistema = value;
    }

    /**
     * Gets the value of the cdVendedor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdVendedor() {
        return cdVendedor;
    }

    /**
     * Sets the value of the cdVendedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdVendedor(Integer value) {
        this.cdVendedor = value;
    }

    /**
     * Gets the value of the cnroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnroContrato() {
        return cnroContrato;
    }

    /**
     * Sets the value of the cnroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnroContrato(String value) {
        this.cnroContrato = value;
    }

    /**
     * Gets the value of the coberturaApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link CoberturaApoliceVo }
     *     
     */
    public CoberturaApoliceVo getCoberturaApoliceVo() {
        return coberturaApoliceVo;
    }

    /**
     * Sets the value of the coberturaApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoberturaApoliceVo }
     *     
     */
    public void setCoberturaApoliceVo(CoberturaApoliceVo value) {
        this.coberturaApoliceVo = value;
    }

    /**
     * Gets the value of the dsDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsDocumento() {
        return dsDocumento;
    }

    /**
     * Sets the value of the dsDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsDocumento(String value) {
        this.dsDocumento = value;
    }

    /**
     * Gets the value of the dsEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsEmail() {
        return dsEmail;
    }

    /**
     * Sets the value of the dsEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsEmail(String value) {
        this.dsEmail = value;
    }

    /**
     * Gets the value of the dtBaseCalculo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtBaseCalculo() {
        return dtBaseCalculo;
    }

    /**
     * Sets the value of the dtBaseCalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtBaseCalculo(String value) {
        this.dtBaseCalculo = value;
    }

    /**
     * Gets the value of the dtEmissao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEmissao() {
        return dtEmissao;
    }

    /**
     * Sets the value of the dtEmissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEmissao(String value) {
        this.dtEmissao = value;
    }

    /**
     * Gets the value of the dtFinalVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFinalVigencia() {
        return dtFinalVigencia;
    }

    /**
     * Sets the value of the dtFinalVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFinalVigencia(String value) {
        this.dtFinalVigencia = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the dtLeasing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtLeasing() {
        return dtLeasing;
    }

    /**
     * Sets the value of the dtLeasing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtLeasing(String value) {
        this.dtLeasing = value;
    }

    /**
     * Gets the value of the dtProcessamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtProcessamento() {
        return dtProcessamento;
    }

    /**
     * Sets the value of the dtProcessamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtProcessamento(String value) {
        this.dtProcessamento = value;
    }

    /**
     * Gets the value of the dtValidadeCartaoCredito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtValidadeCartaoCredito() {
        return dtValidadeCartaoCredito;
    }

    /**
     * Sets the value of the dtValidadeCartaoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtValidadeCartaoCredito(String value) {
        this.dtValidadeCartaoCredito = value;
    }

    /**
     * Gets the value of the flAceitacaoRestrita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAceitacaoRestrita() {
        return flAceitacaoRestrita;
    }

    /**
     * Sets the value of the flAceitacaoRestrita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAceitacaoRestrita(String value) {
        this.flAceitacaoRestrita = value;
    }

    /**
     * Gets the value of the flAutoResidencial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAutoResidencial() {
        return flAutoResidencial;
    }

    /**
     * Sets the value of the flAutoResidencial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAutoResidencial(String value) {
        this.flAutoResidencial = value;
    }

    /**
     * Gets the value of the flImprimeCCB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlImprimeCCB() {
        return flImprimeCCB;
    }

    /**
     * Sets the value of the flImprimeCCB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlImprimeCCB(String value) {
        this.flImprimeCCB = value;
    }

    /**
     * Gets the value of the flIndiceOCT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlIndiceOCT() {
        return flIndiceOCT;
    }

    /**
     * Sets the value of the flIndiceOCT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlIndiceOCT(String value) {
        this.flIndiceOCT = value;
    }

    /**
     * Gets the value of the flNovaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlNovaTarifa() {
        return flNovaTarifa;
    }

    /**
     * Sets the value of the flNovaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlNovaTarifa(String value) {
        this.flNovaTarifa = value;
    }

    /**
     * Gets the value of the flReterDevolucao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlReterDevolucao() {
        return flReterDevolucao;
    }

    /**
     * Sets the value of the flReterDevolucao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlReterDevolucao(String value) {
        this.flReterDevolucao = value;
    }

    /**
     * Gets the value of the flTeleEmpresaFatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlTeleEmpresaFatura() {
        return flTeleEmpresaFatura;
    }

    /**
     * Sets the value of the flTeleEmpresaFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlTeleEmpresaFatura(String value) {
        this.flTeleEmpresaFatura = value;
    }

    /**
     * Gets the value of the listaClausulaApolice property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfClausulaApoliceVo }
     *     
     */
    public ArrayOfClausulaApoliceVo getListaClausulaApolice() {
        return listaClausulaApolice;
    }

    /**
     * Sets the value of the listaClausulaApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfClausulaApoliceVo }
     *     
     */
    public void setListaClausulaApolice(ArrayOfClausulaApoliceVo value) {
        this.listaClausulaApolice = value;
    }

    /**
     * Gets the value of the mensagemErroVo property.
     * 
     * @return
     *     possible object is
     *     {@link MensagemErroVo }
     *     
     */
    public MensagemErroVo getMensagemErroVo() {
        return mensagemErroVo;
    }

    /**
     * Sets the value of the mensagemErroVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MensagemErroVo }
     *     
     */
    public void setMensagemErroVo(MensagemErroVo value) {
        this.mensagemErroVo = value;
    }

    /**
     * Gets the value of the nmOrgaoEmissor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmOrgaoEmissor() {
        return nmOrgaoEmissor;
    }

    /**
     * Sets the value of the nmOrgaoEmissor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmOrgaoEmissor(String value) {
        this.nmOrgaoEmissor = value;
    }

    /**
     * Gets the value of the nuBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuBonus() {
        return nuBonus;
    }

    /**
     * Sets the value of the nuBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuBonus(Integer value) {
        this.nuBonus = value;
    }

    /**
     * Gets the value of the nuCEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCEP() {
        return nuCEP;
    }

    /**
     * Sets the value of the nuCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCEP(String value) {
        this.nuCEP = value;
    }

    /**
     * Gets the value of the nuCartaoCredito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCartaoCredito() {
        return nuCartaoCredito;
    }

    /**
     * Sets the value of the nuCartaoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCartaoCredito(String value) {
        this.nuCartaoCredito = value;
    }

    /**
     * Gets the value of the nuControleLeasing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuControleLeasing() {
        return nuControleLeasing;
    }

    /**
     * Sets the value of the nuControleLeasing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuControleLeasing(String value) {
        this.nuControleLeasing = value;
    }

    /**
     * Gets the value of the nuDiaVencimento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDiaVencimento() {
        return nuDiaVencimento;
    }

    /**
     * Sets the value of the nuDiaVencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDiaVencimento(Integer value) {
        this.nuDiaVencimento = value;
    }

    /**
     * Gets the value of the nuDigitoAgenciaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDigitoAgenciaDebito() {
        return nuDigitoAgenciaDebito;
    }

    /**
     * Sets the value of the nuDigitoAgenciaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDigitoAgenciaDebito(Integer value) {
        this.nuDigitoAgenciaDebito = value;
    }

    /**
     * Gets the value of the nuDigitoContaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDigitoContaDebito() {
        return nuDigitoContaDebito;
    }

    /**
     * Sets the value of the nuDigitoContaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDigitoContaDebito(Integer value) {
        this.nuDigitoContaDebito = value;
    }

    /**
     * Gets the value of the nuDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuDocumento() {
        return nuDocumento;
    }

    /**
     * Sets the value of the nuDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuDocumento(String value) {
        this.nuDocumento = value;
    }

    /**
     * Gets the value of the pagamentoApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link PagamentoApoliceVo }
     *     
     */
    public PagamentoApoliceVo getPagamentoApoliceVo() {
        return pagamentoApoliceVo;
    }

    /**
     * Sets the value of the pagamentoApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagamentoApoliceVo }
     *     
     */
    public void setPagamentoApoliceVo(PagamentoApoliceVo value) {
        this.pagamentoApoliceVo = value;
    }

    /**
     * Gets the value of the parametroApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link ParametroApoliceVo }
     *     
     */
    public ParametroApoliceVo getParametroApoliceVo() {
        return parametroApoliceVo;
    }

    /**
     * Sets the value of the parametroApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametroApoliceVo }
     *     
     */
    public void setParametroApoliceVo(ParametroApoliceVo value) {
        this.parametroApoliceVo = value;
    }

    /**
     * Gets the value of the pcComissaoAPP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAPP() {
        return pcComissaoAPP;
    }

    /**
     * Sets the value of the pcComissaoAPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAPP(Double value) {
        this.pcComissaoAPP = value;
    }

    /**
     * Gets the value of the pcComissaoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAuto() {
        return pcComissaoAuto;
    }

    /**
     * Sets the value of the pcComissaoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAuto(Double value) {
        this.pcComissaoAuto = value;
    }

    /**
     * Gets the value of the pcComissaoRCF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoRCF() {
        return pcComissaoRCF;
    }

    /**
     * Sets the value of the pcComissaoRCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoRCF(Double value) {
        this.pcComissaoRCF = value;
    }

    /**
     * Gets the value of the pcDescontoApp property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoApp() {
        return pcDescontoApp;
    }

    /**
     * Sets the value of the pcDescontoApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoApp(Double value) {
        this.pcDescontoApp = value;
    }

    /**
     * Gets the value of the pcDescontoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoAuto() {
        return pcDescontoAuto;
    }

    /**
     * Sets the value of the pcDescontoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoAuto(Double value) {
        this.pcDescontoAuto = value;
    }

    /**
     * Gets the value of the pcDescontoOnline property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoOnline() {
        return pcDescontoOnline;
    }

    /**
     * Sets the value of the pcDescontoOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoOnline(Double value) {
        this.pcDescontoOnline = value;
    }

    /**
     * Gets the value of the pcDescontoPromocional property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoPromocional() {
        return pcDescontoPromocional;
    }

    /**
     * Sets the value of the pcDescontoPromocional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoPromocional(Double value) {
        this.pcDescontoPromocional = value;
    }

    /**
     * Gets the value of the pcDescontoRcf property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoRcf() {
        return pcDescontoRcf;
    }

    /**
     * Sets the value of the pcDescontoRcf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoRcf(Double value) {
        this.pcDescontoRcf = value;
    }

    /**
     * Gets the value of the pcFatorAgravo property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcFatorAgravo() {
        return pcFatorAgravo;
    }

    /**
     * Sets the value of the pcFatorAgravo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcFatorAgravo(Double value) {
        this.pcFatorAgravo = value;
    }

    /**
     * Gets the value of the perfilApolicePropVo property.
     * 
     * @return
     *     possible object is
     *     {@link PerfilApoliceVo }
     *     
     */
    public PerfilApoliceVo getPerfilApolicePropVo() {
        return perfilApolicePropVo;
    }

    /**
     * Sets the value of the perfilApolicePropVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerfilApoliceVo }
     *     
     */
    public void setPerfilApolicePropVo(PerfilApoliceVo value) {
        this.perfilApolicePropVo = value;
    }

    /**
     * Gets the value of the perfilApoliceSegVo property.
     * 
     * @return
     *     possible object is
     *     {@link PerfilApoliceVo }
     *     
     */
    public PerfilApoliceVo getPerfilApoliceSegVo() {
        return perfilApoliceSegVo;
    }

    /**
     * Sets the value of the perfilApoliceSegVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerfilApoliceVo }
     *     
     */
    public void setPerfilApoliceSegVo(PerfilApoliceVo value) {
        this.perfilApoliceSegVo = value;
    }

    /**
     * Gets the value of the pessoaApolicePropVo property.
     * 
     * @return
     *     possible object is
     *     {@link PessoaApoliceVo }
     *     
     */
    public PessoaApoliceVo getPessoaApolicePropVo() {
        return pessoaApolicePropVo;
    }

    /**
     * Sets the value of the pessoaApolicePropVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PessoaApoliceVo }
     *     
     */
    public void setPessoaApolicePropVo(PessoaApoliceVo value) {
        this.pessoaApolicePropVo = value;
    }

    /**
     * Gets the value of the pessoaApoliceSegVo property.
     * 
     * @return
     *     possible object is
     *     {@link PessoaApoliceVo }
     *     
     */
    public PessoaApoliceVo getPessoaApoliceSegVo() {
        return pessoaApoliceSegVo;
    }

    /**
     * Sets the value of the pessoaApoliceSegVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PessoaApoliceVo }
     *     
     */
    public void setPessoaApoliceSegVo(PessoaApoliceVo value) {
        this.pessoaApoliceSegVo = value;
    }

    /**
     * Gets the value of the renovacaoApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link RenovacaoApoliceVo }
     *     
     */
    public RenovacaoApoliceVo getRenovacaoApoliceVo() {
        return renovacaoApoliceVo;
    }

    /**
     * Sets the value of the renovacaoApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenovacaoApoliceVo }
     *     
     */
    public void setRenovacaoApoliceVo(RenovacaoApoliceVo value) {
        this.renovacaoApoliceVo = value;
    }

    /**
     * Gets the value of the teleEmpresaApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link TeleEmpresaApoliceVo }
     *     
     */
    public TeleEmpresaApoliceVo getTeleEmpresaApoliceVo() {
        return teleEmpresaApoliceVo;
    }

    /**
     * Sets the value of the teleEmpresaApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeleEmpresaApoliceVo }
     *     
     */
    public void setTeleEmpresaApoliceVo(TeleEmpresaApoliceVo value) {
        this.teleEmpresaApoliceVo = value;
    }

    /**
     * Gets the value of the veiculoApoliceVo property.
     * 
     * @return
     *     possible object is
     *     {@link VeiculoApoliceVo }
     *     
     */
    public VeiculoApoliceVo getVeiculoApoliceVo() {
        return veiculoApoliceVo;
    }

    /**
     * Sets the value of the veiculoApoliceVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VeiculoApoliceVo }
     *     
     */
    public void setVeiculoApoliceVo(VeiculoApoliceVo value) {
        this.veiculoApoliceVo = value;
    }

    /**
     * Gets the value of the vlCustoApolice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlCustoApolice() {
        return vlCustoApolice;
    }

    /**
     * Sets the value of the vlCustoApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlCustoApolice(Double value) {
        this.vlCustoApolice = value;
    }

}
