//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalculaCiVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculaCiVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdApolice" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdCiaInterna" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdItem" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdSucursal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculaCiVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdApolice",
    "cdCiaInterna",
    "cdItem",
    "cdSucursal"
})
public class CalculaCiVo {

    protected Integer cdApolice;
    protected Integer cdCiaInterna;
    protected Integer cdItem;
    protected Integer cdSucursal;

    /**
     * Gets the value of the cdApolice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdApolice() {
        return cdApolice;
    }

    /**
     * Sets the value of the cdApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdApolice(Integer value) {
        this.cdApolice = value;
    }

    /**
     * Gets the value of the cdCiaInterna property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdCiaInterna() {
        return cdCiaInterna;
    }

    /**
     * Sets the value of the cdCiaInterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdCiaInterna(Integer value) {
        this.cdCiaInterna = value;
    }

    /**
     * Gets the value of the cdItem property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdItem() {
        return cdItem;
    }

    /**
     * Sets the value of the cdItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdItem(Integer value) {
        this.cdItem = value;
    }

    /**
     * Gets the value of the cdSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdSucursal() {
        return cdSucursal;
    }

    /**
     * Sets the value of the cdSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdSucursal(Integer value) {
        this.cdSucursal = value;
    }

}
