//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClausulasSeguroVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClausulasSeguroVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdClausula" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dsClausula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClausulasSeguroVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdClausula",
    "dsClausula"
})
public class ClausulasSeguroVo {

    protected Integer cdClausula;
    protected String dsClausula;

    /**
     * Gets the value of the cdClausula property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdClausula() {
        return cdClausula;
    }

    /**
     * Sets the value of the cdClausula property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdClausula(Integer value) {
        this.cdClausula = value;
    }

    /**
     * Gets the value of the dsClausula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsClausula() {
        return dsClausula;
    }

    /**
     * Sets the value of the dsClausula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsClausula(String value) {
        this.dsClausula = value;
    }

}
