//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import br.com.bradseg.paol.subscricao.model.vo.ResultadoVo;


/**
 * <p>Java class for CotacaoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CotacaoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdCindMesaNegocio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdContexto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdDescRelacaoSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdEmpresa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdInspetoria" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdItem" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdModalidade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdProdutoCliente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRegiao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRelacaoSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRetornoCrivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdSucursal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPagtoCarne" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaSegurado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoSistema" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cnroContrato" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="coberturaCotacaoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}CoberturaCotacaoVo" minOccurs="0"/>
 *         &lt;element name="coberturaResidencialVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}CoberturaResidencialVo" minOccurs="0"/>
 *         &lt;element name="dtBaseCalculo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtFinalVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtProcessamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flAceitacaoRestrita" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flAutoResidencial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flCartaoCredito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flNovaTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flSucesso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flTeleEmpresaFatura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listaAlertas" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfMensagemAlertaVo" minOccurs="0"/>
 *         &lt;element name="listaClausulas" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfClausulasCotacaoVo" minOccurs="0"/>
 *         &lt;element name="listaParcelamento" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfParcelamentoCotacaoVo" minOccurs="0"/>
 *         &lt;element name="listaParcelamentoResidencial" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfParcelamentoResidencialVo" minOccurs="0"/>
 *         &lt;element name="mensagemErroVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}MensagemErroVo" minOccurs="0"/>
 *         &lt;element name="nmGrupo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCEP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCotacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parametroCotacaoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ParametroCotacaoVo" minOccurs="0"/>
 *         &lt;element name="pcComissaoAPP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoRCF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoApp" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoOnline" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoPromocional" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoRcf" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcFatorAgravo" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="perfilCotacaoPropVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PerfilCotacaoVo" minOccurs="0"/>
 *         &lt;element name="perfilCotacaoSegVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}PerfilCotacaoVo" minOccurs="0"/>
 *         &lt;element name="renovacaoCotacaoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}RenovacaoCotacaoVo" minOccurs="0"/>
 *         &lt;element name="residencialVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ResidencialVo" minOccurs="0"/>
 *         &lt;element name="resultadoDescontoVo" type="{http://vo.model.subscricao.paol.bradseg.com.br}ResultadoVo" minOccurs="0"/>
 *         &lt;element name="veiculoCotacaoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}VeiculoCotacaoVo" minOccurs="0"/>
 *         &lt;element name="vlCustoApolice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CotacaoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdCindMesaNegocio",
    "cdContexto",
    "cdDescRelacaoSeguradoProprietario",
    "cdEmpresa",
    "cdInspetoria",
    "cdItem",
    "cdModalidade",
    "cdProdutoCliente",
    "cdRegiao",
    "cdRelacaoSeguradoProprietario",
    "cdRetornoCrivo",
    "cdSucursal",
    "cdTipoPagtoCarne",
    "cdTipoPessoaProprietario",
    "cdTipoPessoaSegurado",
    "cdTipoSistema",
    "cnroContrato",
    "coberturaCotacaoVo",
    "coberturaResidencialVo",
    "dtBaseCalculo",
    "dtFinalVigencia",
    "dtInicioVigencia",
    "dtProcessamento",
    "flAceitacaoRestrita",
    "flAutoResidencial",
    "flCartaoCredito",
    "flNovaTarifa",
    "flSucesso",
    "flTeleEmpresaFatura",
    "listaAlertas",
    "listaClausulas",
    "listaParcelamento",
    "listaParcelamentoResidencial",
    "mensagemErroVo",
    "nmGrupo",
    "nmProponente",
    "nuCEP",
    "nuCotacao",
    "nuCpfCnpjProponente",
    "nuCpfCnpjProprietario",
    "parametroCotacaoVo",
    "pcComissaoAPP",
    "pcComissaoAuto",
    "pcComissaoRCF",
    "pcDescontoApp",
    "pcDescontoAuto",
    "pcDescontoOnline",
    "pcDescontoPromocional",
    "pcDescontoRcf",
    "pcFatorAgravo",
    "perfilCotacaoPropVo",
    "perfilCotacaoSegVo",
    "renovacaoCotacaoVo",
    "residencialVo",
    "resultadoDescontoVo",
    "veiculoCotacaoVo",
    "vlCustoApolice"
})
public class CotacaoVo {

    protected String cdCindMesaNegocio;
    protected String cdContexto;
    protected String cdDescRelacaoSeguradoProprietario;
    protected Integer cdEmpresa;
    protected Integer cdInspetoria;
    protected Integer cdItem;
    protected String cdModalidade;
    protected Integer cdProdutoCliente;
    protected Integer cdRegiao;
    protected Integer cdRelacaoSeguradoProprietario;
    protected String cdRetornoCrivo;
    protected Integer cdSucursal;
    protected Integer cdTipoPagtoCarne;
    protected String cdTipoPessoaProprietario;
    protected String cdTipoPessoaSegurado;
    protected Integer cdTipoSistema;
    protected Integer cnroContrato;
    protected CoberturaCotacaoVo coberturaCotacaoVo;
    protected CoberturaResidencialVo coberturaResidencialVo;
    protected String dtBaseCalculo;
    protected String dtFinalVigencia;
    protected String dtInicioVigencia;
    protected String dtProcessamento;
    protected String flAceitacaoRestrita;
    protected String flAutoResidencial;
    protected String flCartaoCredito;
    protected String flNovaTarifa;
    protected String flSucesso;
    protected String flTeleEmpresaFatura;
    protected ArrayOfMensagemAlertaVo listaAlertas;
    protected ArrayOfClausulasCotacaoVo listaClausulas;
    protected ArrayOfParcelamentoCotacaoVo listaParcelamento;
    protected ArrayOfParcelamentoResidencialVo listaParcelamentoResidencial;
    protected MensagemErroVo mensagemErroVo;
    protected String nmGrupo;
    protected String nmProponente;
    protected String nuCEP;
    protected Integer nuCotacao;
    protected String nuCpfCnpjProponente;
    protected String nuCpfCnpjProprietario;
    protected ParametroCotacaoVo parametroCotacaoVo;
    protected Double pcComissaoAPP;
    protected Double pcComissaoAuto;
    protected Double pcComissaoRCF;
    protected Double pcDescontoApp;
    protected Double pcDescontoAuto;
    protected Double pcDescontoOnline;
    protected Double pcDescontoPromocional;
    protected Double pcDescontoRcf;
    protected Double pcFatorAgravo;
    protected PerfilCotacaoVo perfilCotacaoPropVo;
    protected PerfilCotacaoVo perfilCotacaoSegVo;
    protected RenovacaoCotacaoVo renovacaoCotacaoVo;
    protected ResidencialVo residencialVo;
    protected ResultadoVo resultadoDescontoVo;
    protected VeiculoCotacaoVo veiculoCotacaoVo;
    protected Double vlCustoApolice;

    /**
     * Gets the value of the cdCindMesaNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdCindMesaNegocio() {
        return cdCindMesaNegocio;
    }

    /**
     * Sets the value of the cdCindMesaNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdCindMesaNegocio(String value) {
        this.cdCindMesaNegocio = value;
    }

    /**
     * Gets the value of the cdContexto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdContexto() {
        return cdContexto;
    }

    /**
     * Sets the value of the cdContexto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdContexto(String value) {
        this.cdContexto = value;
    }

    /**
     * Gets the value of the cdDescRelacaoSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdDescRelacaoSeguradoProprietario() {
        return cdDescRelacaoSeguradoProprietario;
    }

    /**
     * Sets the value of the cdDescRelacaoSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdDescRelacaoSeguradoProprietario(String value) {
        this.cdDescRelacaoSeguradoProprietario = value;
    }

    /**
     * Gets the value of the cdEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEmpresa() {
        return cdEmpresa;
    }

    /**
     * Sets the value of the cdEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEmpresa(Integer value) {
        this.cdEmpresa = value;
    }

    /**
     * Gets the value of the cdInspetoria property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdInspetoria() {
        return cdInspetoria;
    }

    /**
     * Sets the value of the cdInspetoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdInspetoria(Integer value) {
        this.cdInspetoria = value;
    }

    /**
     * Gets the value of the cdItem property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdItem() {
        return cdItem;
    }

    /**
     * Sets the value of the cdItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdItem(Integer value) {
        this.cdItem = value;
    }

    /**
     * Gets the value of the cdModalidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdModalidade() {
        return cdModalidade;
    }

    /**
     * Sets the value of the cdModalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdModalidade(String value) {
        this.cdModalidade = value;
    }

    /**
     * Gets the value of the cdProdutoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdProdutoCliente() {
        return cdProdutoCliente;
    }

    /**
     * Sets the value of the cdProdutoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdProdutoCliente(Integer value) {
        this.cdProdutoCliente = value;
    }

    /**
     * Gets the value of the cdRegiao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRegiao() {
        return cdRegiao;
    }

    /**
     * Sets the value of the cdRegiao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRegiao(Integer value) {
        this.cdRegiao = value;
    }

    /**
     * Gets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRelacaoSeguradoProprietario() {
        return cdRelacaoSeguradoProprietario;
    }

    /**
     * Sets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRelacaoSeguradoProprietario(Integer value) {
        this.cdRelacaoSeguradoProprietario = value;
    }

    /**
     * Gets the value of the cdRetornoCrivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdRetornoCrivo() {
        return cdRetornoCrivo;
    }

    /**
     * Sets the value of the cdRetornoCrivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdRetornoCrivo(String value) {
        this.cdRetornoCrivo = value;
    }

    /**
     * Gets the value of the cdSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdSucursal() {
        return cdSucursal;
    }

    /**
     * Sets the value of the cdSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdSucursal(Integer value) {
        this.cdSucursal = value;
    }

    /**
     * Gets the value of the cdTipoPagtoCarne property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoPagtoCarne() {
        return cdTipoPagtoCarne;
    }

    /**
     * Sets the value of the cdTipoPagtoCarne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoPagtoCarne(Integer value) {
        this.cdTipoPagtoCarne = value;
    }

    /**
     * Gets the value of the cdTipoPessoaProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaProprietario() {
        return cdTipoPessoaProprietario;
    }

    /**
     * Sets the value of the cdTipoPessoaProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaProprietario(String value) {
        this.cdTipoPessoaProprietario = value;
    }

    /**
     * Gets the value of the cdTipoPessoaSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaSegurado() {
        return cdTipoPessoaSegurado;
    }

    /**
     * Sets the value of the cdTipoPessoaSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaSegurado(String value) {
        this.cdTipoPessoaSegurado = value;
    }

    /**
     * Gets the value of the cdTipoSistema property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoSistema() {
        return cdTipoSistema;
    }

    /**
     * Sets the value of the cdTipoSistema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoSistema(Integer value) {
        this.cdTipoSistema = value;
    }

    /**
     * Gets the value of the cnroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCnroContrato() {
        return cnroContrato;
    }

    /**
     * Sets the value of the cnroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCnroContrato(Integer value) {
        this.cnroContrato = value;
    }

    /**
     * Gets the value of the coberturaCotacaoVo property.
     * 
     * @return
     *     possible object is
     *     {@link CoberturaCotacaoVo }
     *     
     */
    public CoberturaCotacaoVo getCoberturaCotacaoVo() {
        return coberturaCotacaoVo;
    }

    /**
     * Sets the value of the coberturaCotacaoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoberturaCotacaoVo }
     *     
     */
    public void setCoberturaCotacaoVo(CoberturaCotacaoVo value) {
        this.coberturaCotacaoVo = value;
    }

    /**
     * Gets the value of the coberturaResidencialVo property.
     * 
     * @return
     *     possible object is
     *     {@link CoberturaResidencialVo }
     *     
     */
    public CoberturaResidencialVo getCoberturaResidencialVo() {
        return coberturaResidencialVo;
    }

    /**
     * Sets the value of the coberturaResidencialVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoberturaResidencialVo }
     *     
     */
    public void setCoberturaResidencialVo(CoberturaResidencialVo value) {
        this.coberturaResidencialVo = value;
    }

    /**
     * Gets the value of the dtBaseCalculo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtBaseCalculo() {
        return dtBaseCalculo;
    }

    /**
     * Sets the value of the dtBaseCalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtBaseCalculo(String value) {
        this.dtBaseCalculo = value;
    }

    /**
     * Gets the value of the dtFinalVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFinalVigencia() {
        return dtFinalVigencia;
    }

    /**
     * Sets the value of the dtFinalVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFinalVigencia(String value) {
        this.dtFinalVigencia = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the dtProcessamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtProcessamento() {
        return dtProcessamento;
    }

    /**
     * Sets the value of the dtProcessamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtProcessamento(String value) {
        this.dtProcessamento = value;
    }

    /**
     * Gets the value of the flAceitacaoRestrita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAceitacaoRestrita() {
        return flAceitacaoRestrita;
    }

    /**
     * Sets the value of the flAceitacaoRestrita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAceitacaoRestrita(String value) {
        this.flAceitacaoRestrita = value;
    }

    /**
     * Gets the value of the flAutoResidencial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAutoResidencial() {
        return flAutoResidencial;
    }

    /**
     * Sets the value of the flAutoResidencial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAutoResidencial(String value) {
        this.flAutoResidencial = value;
    }

    /**
     * Gets the value of the flCartaoCredito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlCartaoCredito() {
        return flCartaoCredito;
    }

    /**
     * Sets the value of the flCartaoCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlCartaoCredito(String value) {
        this.flCartaoCredito = value;
    }

    /**
     * Gets the value of the flNovaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlNovaTarifa() {
        return flNovaTarifa;
    }

    /**
     * Sets the value of the flNovaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlNovaTarifa(String value) {
        this.flNovaTarifa = value;
    }

    /**
     * Gets the value of the flSucesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlSucesso() {
        return flSucesso;
    }

    /**
     * Sets the value of the flSucesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlSucesso(String value) {
        this.flSucesso = value;
    }

    /**
     * Gets the value of the flTeleEmpresaFatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlTeleEmpresaFatura() {
        return flTeleEmpresaFatura;
    }

    /**
     * Sets the value of the flTeleEmpresaFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlTeleEmpresaFatura(String value) {
        this.flTeleEmpresaFatura = value;
    }

    /**
     * Gets the value of the listaAlertas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMensagemAlertaVo }
     *     
     */
    public ArrayOfMensagemAlertaVo getListaAlertas() {
        return listaAlertas;
    }

    /**
     * Sets the value of the listaAlertas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMensagemAlertaVo }
     *     
     */
    public void setListaAlertas(ArrayOfMensagemAlertaVo value) {
        this.listaAlertas = value;
    }

    /**
     * Gets the value of the listaClausulas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfClausulasCotacaoVo }
     *     
     */
    public ArrayOfClausulasCotacaoVo getListaClausulas() {
        return listaClausulas;
    }

    /**
     * Sets the value of the listaClausulas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfClausulasCotacaoVo }
     *     
     */
    public void setListaClausulas(ArrayOfClausulasCotacaoVo value) {
        this.listaClausulas = value;
    }

    /**
     * Gets the value of the listaParcelamento property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfParcelamentoCotacaoVo }
     *     
     */
    public ArrayOfParcelamentoCotacaoVo getListaParcelamento() {
        return listaParcelamento;
    }

    /**
     * Sets the value of the listaParcelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfParcelamentoCotacaoVo }
     *     
     */
    public void setListaParcelamento(ArrayOfParcelamentoCotacaoVo value) {
        this.listaParcelamento = value;
    }

    /**
     * Gets the value of the listaParcelamentoResidencial property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfParcelamentoResidencialVo }
     *     
     */
    public ArrayOfParcelamentoResidencialVo getListaParcelamentoResidencial() {
        return listaParcelamentoResidencial;
    }

    /**
     * Sets the value of the listaParcelamentoResidencial property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfParcelamentoResidencialVo }
     *     
     */
    public void setListaParcelamentoResidencial(ArrayOfParcelamentoResidencialVo value) {
        this.listaParcelamentoResidencial = value;
    }

    /**
     * Gets the value of the mensagemErroVo property.
     * 
     * @return
     *     possible object is
     *     {@link MensagemErroVo }
     *     
     */
    public MensagemErroVo getMensagemErroVo() {
        return mensagemErroVo;
    }

    /**
     * Sets the value of the mensagemErroVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MensagemErroVo }
     *     
     */
    public void setMensagemErroVo(MensagemErroVo value) {
        this.mensagemErroVo = value;
    }

    /**
     * Gets the value of the nmGrupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmGrupo() {
        return nmGrupo;
    }

    /**
     * Sets the value of the nmGrupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmGrupo(String value) {
        this.nmGrupo = value;
    }

    /**
     * Gets the value of the nmProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmProponente() {
        return nmProponente;
    }

    /**
     * Sets the value of the nmProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmProponente(String value) {
        this.nmProponente = value;
    }

    /**
     * Gets the value of the nuCEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCEP() {
        return nuCEP;
    }

    /**
     * Sets the value of the nuCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCEP(String value) {
        this.nuCEP = value;
    }

    /**
     * Gets the value of the nuCotacao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuCotacao() {
        return nuCotacao;
    }

    /**
     * Sets the value of the nuCotacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuCotacao(Integer value) {
        this.nuCotacao = value;
    }

    /**
     * Gets the value of the nuCpfCnpjProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjProponente() {
        return nuCpfCnpjProponente;
    }

    /**
     * Sets the value of the nuCpfCnpjProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjProponente(String value) {
        this.nuCpfCnpjProponente = value;
    }

    /**
     * Gets the value of the nuCpfCnpjProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjProprietario() {
        return nuCpfCnpjProprietario;
    }

    /**
     * Sets the value of the nuCpfCnpjProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjProprietario(String value) {
        this.nuCpfCnpjProprietario = value;
    }

    /**
     * Gets the value of the parametroCotacaoVo property.
     * 
     * @return
     *     possible object is
     *     {@link ParametroCotacaoVo }
     *     
     */
    public ParametroCotacaoVo getParametroCotacaoVo() {
        return parametroCotacaoVo;
    }

    /**
     * Sets the value of the parametroCotacaoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametroCotacaoVo }
     *     
     */
    public void setParametroCotacaoVo(ParametroCotacaoVo value) {
        this.parametroCotacaoVo = value;
    }

    /**
     * Gets the value of the pcComissaoAPP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAPP() {
        return pcComissaoAPP;
    }

    /**
     * Sets the value of the pcComissaoAPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAPP(Double value) {
        this.pcComissaoAPP = value;
    }

    /**
     * Gets the value of the pcComissaoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAuto() {
        return pcComissaoAuto;
    }

    /**
     * Sets the value of the pcComissaoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAuto(Double value) {
        this.pcComissaoAuto = value;
    }

    /**
     * Gets the value of the pcComissaoRCF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoRCF() {
        return pcComissaoRCF;
    }

    /**
     * Sets the value of the pcComissaoRCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoRCF(Double value) {
        this.pcComissaoRCF = value;
    }

    /**
     * Gets the value of the pcDescontoApp property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoApp() {
        return pcDescontoApp;
    }

    /**
     * Sets the value of the pcDescontoApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoApp(Double value) {
        this.pcDescontoApp = value;
    }

    /**
     * Gets the value of the pcDescontoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoAuto() {
        return pcDescontoAuto;
    }

    /**
     * Sets the value of the pcDescontoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoAuto(Double value) {
        this.pcDescontoAuto = value;
    }

    /**
     * Gets the value of the pcDescontoOnline property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoOnline() {
        return pcDescontoOnline;
    }

    /**
     * Sets the value of the pcDescontoOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoOnline(Double value) {
        this.pcDescontoOnline = value;
    }

    /**
     * Gets the value of the pcDescontoPromocional property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoPromocional() {
        return pcDescontoPromocional;
    }

    /**
     * Sets the value of the pcDescontoPromocional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoPromocional(Double value) {
        this.pcDescontoPromocional = value;
    }

    /**
     * Gets the value of the pcDescontoRcf property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoRcf() {
        return pcDescontoRcf;
    }

    /**
     * Sets the value of the pcDescontoRcf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoRcf(Double value) {
        this.pcDescontoRcf = value;
    }

    /**
     * Gets the value of the pcFatorAgravo property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcFatorAgravo() {
        return pcFatorAgravo;
    }

    /**
     * Sets the value of the pcFatorAgravo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcFatorAgravo(Double value) {
        this.pcFatorAgravo = value;
    }

    /**
     * Gets the value of the perfilCotacaoPropVo property.
     * 
     * @return
     *     possible object is
     *     {@link PerfilCotacaoVo }
     *     
     */
    public PerfilCotacaoVo getPerfilCotacaoPropVo() {
        return perfilCotacaoPropVo;
    }

    /**
     * Sets the value of the perfilCotacaoPropVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerfilCotacaoVo }
     *     
     */
    public void setPerfilCotacaoPropVo(PerfilCotacaoVo value) {
        this.perfilCotacaoPropVo = value;
    }

    /**
     * Gets the value of the perfilCotacaoSegVo property.
     * 
     * @return
     *     possible object is
     *     {@link PerfilCotacaoVo }
     *     
     */
    public PerfilCotacaoVo getPerfilCotacaoSegVo() {
        return perfilCotacaoSegVo;
    }

    /**
     * Sets the value of the perfilCotacaoSegVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerfilCotacaoVo }
     *     
     */
    public void setPerfilCotacaoSegVo(PerfilCotacaoVo value) {
        this.perfilCotacaoSegVo = value;
    }

    /**
     * Gets the value of the renovacaoCotacaoVo property.
     * 
     * @return
     *     possible object is
     *     {@link RenovacaoCotacaoVo }
     *     
     */
    public RenovacaoCotacaoVo getRenovacaoCotacaoVo() {
        return renovacaoCotacaoVo;
    }

    /**
     * Sets the value of the renovacaoCotacaoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenovacaoCotacaoVo }
     *     
     */
    public void setRenovacaoCotacaoVo(RenovacaoCotacaoVo value) {
        this.renovacaoCotacaoVo = value;
    }

    /**
     * Gets the value of the residencialVo property.
     * 
     * @return
     *     possible object is
     *     {@link ResidencialVo }
     *     
     */
    public ResidencialVo getResidencialVo() {
        return residencialVo;
    }

    /**
     * Sets the value of the residencialVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidencialVo }
     *     
     */
    public void setResidencialVo(ResidencialVo value) {
        this.residencialVo = value;
    }

    /**
     * Gets the value of the resultadoDescontoVo property.
     * 
     * @return
     *     possible object is
     *     {@link ResultadoVo }
     *     
     */
    public ResultadoVo getResultadoDescontoVo() {
        return resultadoDescontoVo;
    }

    /**
     * Sets the value of the resultadoDescontoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultadoVo }
     *     
     */
    public void setResultadoDescontoVo(ResultadoVo value) {
        this.resultadoDescontoVo = value;
    }

    /**
     * Gets the value of the veiculoCotacaoVo property.
     * 
     * @return
     *     possible object is
     *     {@link VeiculoCotacaoVo }
     *     
     */
    public VeiculoCotacaoVo getVeiculoCotacaoVo() {
        return veiculoCotacaoVo;
    }

    /**
     * Sets the value of the veiculoCotacaoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VeiculoCotacaoVo }
     *     
     */
    public void setVeiculoCotacaoVo(VeiculoCotacaoVo value) {
        this.veiculoCotacaoVo = value;
    }

    /**
     * Gets the value of the vlCustoApolice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlCustoApolice() {
        return vlCustoApolice;
    }

    /**
     * Sets the value of the vlCustoApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlCustoApolice(Double value) {
        this.vlCustoApolice = value;
    }

}
