//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DadosSeguradoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DadosSeguradoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdAtividadePrinc" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdClasseBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdCobertura18a25anos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdEstadoCivil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdGaragemEmCasa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdMaisQUmVeicResid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdOrgaoEmissor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdPossuiFilhosAte17anor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdProfissao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdSexo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsAtividadePrinc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtEmissao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtNascimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enderecoCobranca" type="{http://vo.model.calculoauto.paol.bradseg.com.br}DadosEnderecoVo" minOccurs="0"/>
 *         &lt;element name="enderecoRisco" type="{http://vo.model.calculoauto.paol.bradseg.com.br}DadosEnderecoVo" minOccurs="0"/>
 *         &lt;element name="nmSegurado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomePropietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjPropietario" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="nuIdentidade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telefoneCelular" type="{http://vo.model.calculoauto.paol.bradseg.com.br}DadosTelefoneVo" minOccurs="0"/>
 *         &lt;element name="telefoneComercial" type="{http://vo.model.calculoauto.paol.bradseg.com.br}DadosTelefoneVo" minOccurs="0"/>
 *         &lt;element name="telefoneResindencial" type="{http://vo.model.calculoauto.paol.bradseg.com.br}DadosTelefoneVo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DadosSeguradoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdAtividadePrinc",
    "cdClasseBonus",
    "cdCobertura18A25Anos",
    "cdEstadoCivil",
    "cdGaragemEmCasa",
    "cdMaisQUmVeicResid",
    "cdOrgaoEmissor",
    "cdPossuiFilhosAte17Anor",
    "cdProfissao",
    "cdSexo",
    "cdTipoPessoa",
    "dsAtividadePrinc",
    "dtEmissao",
    "dtNascimento",
    "email",
    "enderecoCobranca",
    "enderecoRisco",
    "nmSegurado",
    "nomePropietario",
    "nuCpfCnpjPropietario",
    "nuCpfCnpjSegurado",
    "nuIdentidade",
    "telefoneCelular",
    "telefoneComercial",
    "telefoneResindencial"
})
public class DadosSeguradoVo {

    protected Integer cdAtividadePrinc;
    protected Integer cdClasseBonus;
    @XmlElement(name = "cdCobertura18a25anos")
    protected String cdCobertura18A25Anos;
    protected String cdEstadoCivil;
    protected String cdGaragemEmCasa;
    protected String cdMaisQUmVeicResid;
    protected String cdOrgaoEmissor;
    @XmlElement(name = "cdPossuiFilhosAte17anor")
    protected String cdPossuiFilhosAte17Anor;
    protected String cdProfissao;
    protected String cdSexo;
    protected String cdTipoPessoa;
    protected String dsAtividadePrinc;
    protected String dtEmissao;
    protected String dtNascimento;
    protected String email;
    protected DadosEnderecoVo enderecoCobranca;
    protected DadosEnderecoVo enderecoRisco;
    protected String nmSegurado;
    protected String nomePropietario;
    protected Long nuCpfCnpjPropietario;
    protected Long nuCpfCnpjSegurado;
    protected String nuIdentidade;
    protected DadosTelefoneVo telefoneCelular;
    protected DadosTelefoneVo telefoneComercial;
    protected DadosTelefoneVo telefoneResindencial;

    /**
     * Gets the value of the cdAtividadePrinc property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdAtividadePrinc() {
        return cdAtividadePrinc;
    }

    /**
     * Sets the value of the cdAtividadePrinc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdAtividadePrinc(Integer value) {
        this.cdAtividadePrinc = value;
    }

    /**
     * Gets the value of the cdClasseBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdClasseBonus() {
        return cdClasseBonus;
    }

    /**
     * Sets the value of the cdClasseBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdClasseBonus(Integer value) {
        this.cdClasseBonus = value;
    }

    /**
     * Gets the value of the cdCobertura18A25Anos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdCobertura18A25Anos() {
        return cdCobertura18A25Anos;
    }

    /**
     * Sets the value of the cdCobertura18A25Anos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdCobertura18A25Anos(String value) {
        this.cdCobertura18A25Anos = value;
    }

    /**
     * Gets the value of the cdEstadoCivil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdEstadoCivil() {
        return cdEstadoCivil;
    }

    /**
     * Sets the value of the cdEstadoCivil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdEstadoCivil(String value) {
        this.cdEstadoCivil = value;
    }

    /**
     * Gets the value of the cdGaragemEmCasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdGaragemEmCasa() {
        return cdGaragemEmCasa;
    }

    /**
     * Sets the value of the cdGaragemEmCasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdGaragemEmCasa(String value) {
        this.cdGaragemEmCasa = value;
    }

    /**
     * Gets the value of the cdMaisQUmVeicResid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdMaisQUmVeicResid() {
        return cdMaisQUmVeicResid;
    }

    /**
     * Sets the value of the cdMaisQUmVeicResid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdMaisQUmVeicResid(String value) {
        this.cdMaisQUmVeicResid = value;
    }

    /**
     * Gets the value of the cdOrgaoEmissor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdOrgaoEmissor() {
        return cdOrgaoEmissor;
    }

    /**
     * Sets the value of the cdOrgaoEmissor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdOrgaoEmissor(String value) {
        this.cdOrgaoEmissor = value;
    }

    /**
     * Gets the value of the cdPossuiFilhosAte17Anor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdPossuiFilhosAte17Anor() {
        return cdPossuiFilhosAte17Anor;
    }

    /**
     * Sets the value of the cdPossuiFilhosAte17Anor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdPossuiFilhosAte17Anor(String value) {
        this.cdPossuiFilhosAte17Anor = value;
    }

    /**
     * Gets the value of the cdProfissao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdProfissao() {
        return cdProfissao;
    }

    /**
     * Sets the value of the cdProfissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdProfissao(String value) {
        this.cdProfissao = value;
    }

    /**
     * Gets the value of the cdSexo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdSexo() {
        return cdSexo;
    }

    /**
     * Sets the value of the cdSexo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdSexo(String value) {
        this.cdSexo = value;
    }

    /**
     * Gets the value of the cdTipoPessoa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoa() {
        return cdTipoPessoa;
    }

    /**
     * Sets the value of the cdTipoPessoa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoa(String value) {
        this.cdTipoPessoa = value;
    }

    /**
     * Gets the value of the dsAtividadePrinc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsAtividadePrinc() {
        return dsAtividadePrinc;
    }

    /**
     * Sets the value of the dsAtividadePrinc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsAtividadePrinc(String value) {
        this.dsAtividadePrinc = value;
    }

    /**
     * Gets the value of the dtEmissao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEmissao() {
        return dtEmissao;
    }

    /**
     * Sets the value of the dtEmissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEmissao(String value) {
        this.dtEmissao = value;
    }

    /**
     * Gets the value of the dtNascimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtNascimento() {
        return dtNascimento;
    }

    /**
     * Sets the value of the dtNascimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtNascimento(String value) {
        this.dtNascimento = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the enderecoCobranca property.
     * 
     * @return
     *     possible object is
     *     {@link DadosEnderecoVo }
     *     
     */
    public DadosEnderecoVo getEnderecoCobranca() {
        return enderecoCobranca;
    }

    /**
     * Sets the value of the enderecoCobranca property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosEnderecoVo }
     *     
     */
    public void setEnderecoCobranca(DadosEnderecoVo value) {
        this.enderecoCobranca = value;
    }

    /**
     * Gets the value of the enderecoRisco property.
     * 
     * @return
     *     possible object is
     *     {@link DadosEnderecoVo }
     *     
     */
    public DadosEnderecoVo getEnderecoRisco() {
        return enderecoRisco;
    }

    /**
     * Sets the value of the enderecoRisco property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosEnderecoVo }
     *     
     */
    public void setEnderecoRisco(DadosEnderecoVo value) {
        this.enderecoRisco = value;
    }

    /**
     * Gets the value of the nmSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmSegurado() {
        return nmSegurado;
    }

    /**
     * Sets the value of the nmSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmSegurado(String value) {
        this.nmSegurado = value;
    }

    /**
     * Gets the value of the nomePropietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePropietario() {
        return nomePropietario;
    }

    /**
     * Sets the value of the nomePropietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePropietario(String value) {
        this.nomePropietario = value;
    }

    /**
     * Gets the value of the nuCpfCnpjPropietario property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNuCpfCnpjPropietario() {
        return nuCpfCnpjPropietario;
    }

    /**
     * Sets the value of the nuCpfCnpjPropietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNuCpfCnpjPropietario(Long value) {
        this.nuCpfCnpjPropietario = value;
    }

    /**
     * Gets the value of the nuCpfCnpjSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNuCpfCnpjSegurado() {
        return nuCpfCnpjSegurado;
    }

    /**
     * Sets the value of the nuCpfCnpjSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNuCpfCnpjSegurado(Long value) {
        this.nuCpfCnpjSegurado = value;
    }

    /**
     * Gets the value of the nuIdentidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuIdentidade() {
        return nuIdentidade;
    }

    /**
     * Sets the value of the nuIdentidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuIdentidade(String value) {
        this.nuIdentidade = value;
    }

    /**
     * Gets the value of the telefoneCelular property.
     * 
     * @return
     *     possible object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public DadosTelefoneVo getTelefoneCelular() {
        return telefoneCelular;
    }

    /**
     * Sets the value of the telefoneCelular property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public void setTelefoneCelular(DadosTelefoneVo value) {
        this.telefoneCelular = value;
    }

    /**
     * Gets the value of the telefoneComercial property.
     * 
     * @return
     *     possible object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public DadosTelefoneVo getTelefoneComercial() {
        return telefoneComercial;
    }

    /**
     * Sets the value of the telefoneComercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public void setTelefoneComercial(DadosTelefoneVo value) {
        this.telefoneComercial = value;
    }

    /**
     * Gets the value of the telefoneResindencial property.
     * 
     * @return
     *     possible object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public DadosTelefoneVo getTelefoneResindencial() {
        return telefoneResindencial;
    }

    /**
     * Sets the value of the telefoneResindencial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosTelefoneVo }
     *     
     */
    public void setTelefoneResindencial(DadosTelefoneVo value) {
        this.telefoneResindencial = value;
    }

}
