//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DadosEnderecoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DadosEnderecoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdUf" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsBairro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsComplemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsMunicipio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmLogradouro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCep" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuLogradouro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tpLogradouro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DadosEnderecoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdUf",
    "dsBairro",
    "dsComplemento",
    "dsMunicipio",
    "nmLogradouro",
    "nuCep",
    "nuLogradouro",
    "tpLogradouro"
})
public class DadosEnderecoVo {

    protected String cdUf;
    protected String dsBairro;
    protected String dsComplemento;
    protected String dsMunicipio;
    protected String nmLogradouro;
    protected Integer nuCep;
    protected Integer nuLogradouro;
    protected String tpLogradouro;

    /**
     * Gets the value of the cdUf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdUf() {
        return cdUf;
    }

    /**
     * Sets the value of the cdUf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdUf(String value) {
        this.cdUf = value;
    }

    /**
     * Gets the value of the dsBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsBairro() {
        return dsBairro;
    }

    /**
     * Sets the value of the dsBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsBairro(String value) {
        this.dsBairro = value;
    }

    /**
     * Gets the value of the dsComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsComplemento() {
        return dsComplemento;
    }

    /**
     * Sets the value of the dsComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsComplemento(String value) {
        this.dsComplemento = value;
    }

    /**
     * Gets the value of the dsMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsMunicipio() {
        return dsMunicipio;
    }

    /**
     * Sets the value of the dsMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsMunicipio(String value) {
        this.dsMunicipio = value;
    }

    /**
     * Gets the value of the nmLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmLogradouro() {
        return nmLogradouro;
    }

    /**
     * Sets the value of the nmLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmLogradouro(String value) {
        this.nmLogradouro = value;
    }

    /**
     * Gets the value of the nuCep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuCep() {
        return nuCep;
    }

    /**
     * Sets the value of the nuCep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuCep(Integer value) {
        this.nuCep = value;
    }

    /**
     * Gets the value of the nuLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuLogradouro() {
        return nuLogradouro;
    }

    /**
     * Sets the value of the nuLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuLogradouro(Integer value) {
        this.nuLogradouro = value;
    }

    /**
     * Gets the value of the tpLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpLogradouro() {
        return tpLogradouro;
    }

    /**
     * Sets the value of the tpLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpLogradouro(String value) {
        this.tpLogradouro = value;
    }

}
