//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ECalculoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECalculoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ECoberturaVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ECoberturaVo" minOccurs="0"/>
 *         &lt;element name="EParametroVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}EParametroVo" minOccurs="0"/>
 *         &lt;element name="EPerfilProprietarioVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}EPerfilVo" minOccurs="0"/>
 *         &lt;element name="EPerfilSeguradoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}EPerfilVo" minOccurs="0"/>
 *         &lt;element name="ERenovacaoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ERenovacaoVo" minOccurs="0"/>
 *         &lt;element name="EVeiculoVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}EVeiculoVo" minOccurs="0"/>
 *         &lt;element name="cdCindMesaNegocio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdDescRelacaoSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdEmpresa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdInspetoria" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdModalidade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdProdutoCliente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRelacaoSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdSucursal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPagtoCarne" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaSegurado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cdTipoSistema" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cnroContrato" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dtFinalVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtProcessamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flNovaTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flTeleEmpresaFatura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCEP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjProprietario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcComissaoAPP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoRCF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoAPP" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoAuto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoRCF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pctDescontoPromocional" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="residencialVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ResidencialVo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECalculoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "eCoberturaVo",
    "eParametroVo",
    "ePerfilProprietarioVo",
    "ePerfilSeguradoVo",
    "eRenovacaoVo",
    "eVeiculoVo",
    "cdCindMesaNegocio",
    "cdDescRelacaoSeguradoProprietario",
    "cdEmpresa",
    "cdInspetoria",
    "cdModalidade",
    "cdProdutoCliente",
    "cdRelacaoSeguradoProprietario",
    "cdSucursal",
    "cdTipoPagtoCarne",
    "cdTipoPessoaProprietario",
    "cdTipoPessoaSegurado",
    "cdTipoSistema",
    "cnroContrato",
    "dtFinalVigencia",
    "dtInicioVigencia",
    "dtProcessamento",
    "flNovaTarifa",
    "flTeleEmpresaFatura",
    "nmProponente",
    "nuCEP",
    "nuCpfCnpjProponente",
    "nuCpfCnpjProprietario",
    "pcComissaoAPP",
    "pcComissaoAuto",
    "pcComissaoRCF",
    "pcDescontoAPP",
    "pcDescontoAuto",
    "pcDescontoRCF",
    "pctDescontoPromocional",
    "residencialVo"
})
public class ECalculoVo {

    @XmlElement(name = "ECoberturaVo")
    protected ECoberturaVo eCoberturaVo;
    @XmlElement(name = "EParametroVo")
    protected EParametroVo eParametroVo;
    @XmlElement(name = "EPerfilProprietarioVo")
    protected EPerfilVo ePerfilProprietarioVo;
    @XmlElement(name = "EPerfilSeguradoVo")
    protected EPerfilVo ePerfilSeguradoVo;
    @XmlElement(name = "ERenovacaoVo")
    protected ERenovacaoVo eRenovacaoVo;
    @XmlElement(name = "EVeiculoVo")
    protected EVeiculoVo eVeiculoVo;
    protected String cdCindMesaNegocio;
    protected String cdDescRelacaoSeguradoProprietario;
    protected Integer cdEmpresa;
    protected Integer cdInspetoria;
    protected String cdModalidade;
    protected Integer cdProdutoCliente;
    protected Integer cdRelacaoSeguradoProprietario;
    protected Integer cdSucursal;
    protected Integer cdTipoPagtoCarne;
    protected String cdTipoPessoaProprietario;
    protected String cdTipoPessoaSegurado;
    protected Integer cdTipoSistema;
    protected Integer cnroContrato;
    protected String dtFinalVigencia;
    protected String dtInicioVigencia;
    protected String dtProcessamento;
    protected String flNovaTarifa;
    protected String flTeleEmpresaFatura;
    protected String nmProponente;
    protected String nuCEP;
    protected String nuCpfCnpjProponente;
    protected String nuCpfCnpjProprietario;
    protected Double pcComissaoAPP;
    protected Double pcComissaoAuto;
    protected Double pcComissaoRCF;
    protected Double pcDescontoAPP;
    protected Double pcDescontoAuto;
    protected Double pcDescontoRCF;
    protected Double pctDescontoPromocional;
    protected ResidencialVo residencialVo;

    /**
     * Gets the value of the eCoberturaVo property.
     * 
     * @return
     *     possible object is
     *     {@link ECoberturaVo }
     *     
     */
    public ECoberturaVo getECoberturaVo() {
        return eCoberturaVo;
    }

    /**
     * Sets the value of the eCoberturaVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECoberturaVo }
     *     
     */
    public void setECoberturaVo(ECoberturaVo value) {
        this.eCoberturaVo = value;
    }

    /**
     * Gets the value of the eParametroVo property.
     * 
     * @return
     *     possible object is
     *     {@link EParametroVo }
     *     
     */
    public EParametroVo getEParametroVo() {
        return eParametroVo;
    }

    /**
     * Sets the value of the eParametroVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EParametroVo }
     *     
     */
    public void setEParametroVo(EParametroVo value) {
        this.eParametroVo = value;
    }

    /**
     * Gets the value of the ePerfilProprietarioVo property.
     * 
     * @return
     *     possible object is
     *     {@link EPerfilVo }
     *     
     */
    public EPerfilVo getEPerfilProprietarioVo() {
        return ePerfilProprietarioVo;
    }

    /**
     * Sets the value of the ePerfilProprietarioVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPerfilVo }
     *     
     */
    public void setEPerfilProprietarioVo(EPerfilVo value) {
        this.ePerfilProprietarioVo = value;
    }

    /**
     * Gets the value of the ePerfilSeguradoVo property.
     * 
     * @return
     *     possible object is
     *     {@link EPerfilVo }
     *     
     */
    public EPerfilVo getEPerfilSeguradoVo() {
        return ePerfilSeguradoVo;
    }

    /**
     * Sets the value of the ePerfilSeguradoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPerfilVo }
     *     
     */
    public void setEPerfilSeguradoVo(EPerfilVo value) {
        this.ePerfilSeguradoVo = value;
    }

    /**
     * Gets the value of the eRenovacaoVo property.
     * 
     * @return
     *     possible object is
     *     {@link ERenovacaoVo }
     *     
     */
    public ERenovacaoVo getERenovacaoVo() {
        return eRenovacaoVo;
    }

    /**
     * Sets the value of the eRenovacaoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERenovacaoVo }
     *     
     */
    public void setERenovacaoVo(ERenovacaoVo value) {
        this.eRenovacaoVo = value;
    }

    /**
     * Gets the value of the eVeiculoVo property.
     * 
     * @return
     *     possible object is
     *     {@link EVeiculoVo }
     *     
     */
    public EVeiculoVo getEVeiculoVo() {
        return eVeiculoVo;
    }

    /**
     * Sets the value of the eVeiculoVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVeiculoVo }
     *     
     */
    public void setEVeiculoVo(EVeiculoVo value) {
        this.eVeiculoVo = value;
    }

    /**
     * Gets the value of the cdCindMesaNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdCindMesaNegocio() {
        return cdCindMesaNegocio;
    }

    /**
     * Sets the value of the cdCindMesaNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdCindMesaNegocio(String value) {
        this.cdCindMesaNegocio = value;
    }

    /**
     * Gets the value of the cdDescRelacaoSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdDescRelacaoSeguradoProprietario() {
        return cdDescRelacaoSeguradoProprietario;
    }

    /**
     * Sets the value of the cdDescRelacaoSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdDescRelacaoSeguradoProprietario(String value) {
        this.cdDescRelacaoSeguradoProprietario = value;
    }

    /**
     * Gets the value of the cdEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEmpresa() {
        return cdEmpresa;
    }

    /**
     * Sets the value of the cdEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEmpresa(Integer value) {
        this.cdEmpresa = value;
    }

    /**
     * Gets the value of the cdInspetoria property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdInspetoria() {
        return cdInspetoria;
    }

    /**
     * Sets the value of the cdInspetoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdInspetoria(Integer value) {
        this.cdInspetoria = value;
    }

    /**
     * Gets the value of the cdModalidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdModalidade() {
        return cdModalidade;
    }

    /**
     * Sets the value of the cdModalidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdModalidade(String value) {
        this.cdModalidade = value;
    }

    /**
     * Gets the value of the cdProdutoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdProdutoCliente() {
        return cdProdutoCliente;
    }

    /**
     * Sets the value of the cdProdutoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdProdutoCliente(Integer value) {
        this.cdProdutoCliente = value;
    }

    /**
     * Gets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRelacaoSeguradoProprietario() {
        return cdRelacaoSeguradoProprietario;
    }

    /**
     * Sets the value of the cdRelacaoSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRelacaoSeguradoProprietario(Integer value) {
        this.cdRelacaoSeguradoProprietario = value;
    }

    /**
     * Gets the value of the cdSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdSucursal() {
        return cdSucursal;
    }

    /**
     * Sets the value of the cdSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdSucursal(Integer value) {
        this.cdSucursal = value;
    }

    /**
     * Gets the value of the cdTipoPagtoCarne property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoPagtoCarne() {
        return cdTipoPagtoCarne;
    }

    /**
     * Sets the value of the cdTipoPagtoCarne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoPagtoCarne(Integer value) {
        this.cdTipoPagtoCarne = value;
    }

    /**
     * Gets the value of the cdTipoPessoaProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaProprietario() {
        return cdTipoPessoaProprietario;
    }

    /**
     * Sets the value of the cdTipoPessoaProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaProprietario(String value) {
        this.cdTipoPessoaProprietario = value;
    }

    /**
     * Gets the value of the cdTipoPessoaSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaSegurado() {
        return cdTipoPessoaSegurado;
    }

    /**
     * Sets the value of the cdTipoPessoaSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaSegurado(String value) {
        this.cdTipoPessoaSegurado = value;
    }

    /**
     * Gets the value of the cdTipoSistema property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoSistema() {
        return cdTipoSistema;
    }

    /**
     * Sets the value of the cdTipoSistema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoSistema(Integer value) {
        this.cdTipoSistema = value;
    }

    /**
     * Gets the value of the cnroContrato property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCnroContrato() {
        return cnroContrato;
    }

    /**
     * Sets the value of the cnroContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCnroContrato(Integer value) {
        this.cnroContrato = value;
    }

    /**
     * Gets the value of the dtFinalVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFinalVigencia() {
        return dtFinalVigencia;
    }

    /**
     * Sets the value of the dtFinalVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFinalVigencia(String value) {
        this.dtFinalVigencia = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the dtProcessamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtProcessamento() {
        return dtProcessamento;
    }

    /**
     * Sets the value of the dtProcessamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtProcessamento(String value) {
        this.dtProcessamento = value;
    }

    /**
     * Gets the value of the flNovaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlNovaTarifa() {
        return flNovaTarifa;
    }

    /**
     * Sets the value of the flNovaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlNovaTarifa(String value) {
        this.flNovaTarifa = value;
    }

    /**
     * Gets the value of the flTeleEmpresaFatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlTeleEmpresaFatura() {
        return flTeleEmpresaFatura;
    }

    /**
     * Sets the value of the flTeleEmpresaFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlTeleEmpresaFatura(String value) {
        this.flTeleEmpresaFatura = value;
    }

    /**
     * Gets the value of the nmProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmProponente() {
        return nmProponente;
    }

    /**
     * Sets the value of the nmProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmProponente(String value) {
        this.nmProponente = value;
    }

    /**
     * Gets the value of the nuCEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCEP() {
        return nuCEP;
    }

    /**
     * Sets the value of the nuCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCEP(String value) {
        this.nuCEP = value;
    }

    /**
     * Gets the value of the nuCpfCnpjProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjProponente() {
        return nuCpfCnpjProponente;
    }

    /**
     * Sets the value of the nuCpfCnpjProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjProponente(String value) {
        this.nuCpfCnpjProponente = value;
    }

    /**
     * Gets the value of the nuCpfCnpjProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjProprietario() {
        return nuCpfCnpjProprietario;
    }

    /**
     * Sets the value of the nuCpfCnpjProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjProprietario(String value) {
        this.nuCpfCnpjProprietario = value;
    }

    /**
     * Gets the value of the pcComissaoAPP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAPP() {
        return pcComissaoAPP;
    }

    /**
     * Sets the value of the pcComissaoAPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAPP(Double value) {
        this.pcComissaoAPP = value;
    }

    /**
     * Gets the value of the pcComissaoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoAuto() {
        return pcComissaoAuto;
    }

    /**
     * Sets the value of the pcComissaoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoAuto(Double value) {
        this.pcComissaoAuto = value;
    }

    /**
     * Gets the value of the pcComissaoRCF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoRCF() {
        return pcComissaoRCF;
    }

    /**
     * Sets the value of the pcComissaoRCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoRCF(Double value) {
        this.pcComissaoRCF = value;
    }

    /**
     * Gets the value of the pcDescontoAPP property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoAPP() {
        return pcDescontoAPP;
    }

    /**
     * Sets the value of the pcDescontoAPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoAPP(Double value) {
        this.pcDescontoAPP = value;
    }

    /**
     * Gets the value of the pcDescontoAuto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoAuto() {
        return pcDescontoAuto;
    }

    /**
     * Sets the value of the pcDescontoAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoAuto(Double value) {
        this.pcDescontoAuto = value;
    }

    /**
     * Gets the value of the pcDescontoRCF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoRCF() {
        return pcDescontoRCF;
    }

    /**
     * Sets the value of the pcDescontoRCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoRCF(Double value) {
        this.pcDescontoRCF = value;
    }

    /**
     * Gets the value of the pctDescontoPromocional property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPctDescontoPromocional() {
        return pctDescontoPromocional;
    }

    /**
     * Sets the value of the pctDescontoPromocional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPctDescontoPromocional(Double value) {
        this.pctDescontoPromocional = value;
    }

    /**
     * Gets the value of the residencialVo property.
     * 
     * @return
     *     possible object is
     *     {@link ResidencialVo }
     *     
     */
    public ResidencialVo getResidencialVo() {
        return residencialVo;
    }

    /**
     * Sets the value of the residencialVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidencialVo }
     *     
     */
    public void setResidencialVo(ResidencialVo value) {
        this.residencialVo = value;
    }

}
