//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ECoberturaEndossoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECoberturaEndossoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdClausulaAssistencia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdClausulaCarroReserva" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdClausulaVidros" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdExtensaoRCFColaborador" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdRCTR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdZeroKm" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dtFinalExtPerimetro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtInicioExtPerimetro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flCoberturaSP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flDespesasExtraordinaria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flExtensaoRCFReboque" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flExtensaoRCFVeiculo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flRemoveCl67" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isAppInvalidez" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isAppMorte" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isBlindagem" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isCarroceria" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isCasco" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isDanosCorporais" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isDanosMateriais" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isDanosMorais" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isEquipamentos" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isGarantiaUnica" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isKitGas" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="nuDiasDiariaParalisacao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDiasExtensaoPerimetro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="vlDiariaParalisacao" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECoberturaEndossoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdClausulaAssistencia",
    "cdClausulaCarroReserva",
    "cdClausulaVidros",
    "cdExtensaoRCFColaborador",
    "cdRCTR",
    "cdZeroKm",
    "dtFinalExtPerimetro",
    "dtInicioExtPerimetro",
    "flCoberturaSP",
    "flDespesasExtraordinaria",
    "flExtensaoRCFReboque",
    "flExtensaoRCFVeiculo",
    "flRemoveCl67",
    "isAppInvalidez",
    "isAppMorte",
    "isBlindagem",
    "isCarroceria",
    "isCasco",
    "isDanosCorporais",
    "isDanosMateriais",
    "isDanosMorais",
    "isEquipamentos",
    "isGarantiaUnica",
    "isKitGas",
    "nuDiasDiariaParalisacao",
    "nuDiasExtensaoPerimetro",
    "vlDiariaParalisacao"
})
public class ECoberturaEndossoVo {

    protected Integer cdClausulaAssistencia;
    protected Integer cdClausulaCarroReserva;
    protected Integer cdClausulaVidros;
    protected Integer cdExtensaoRCFColaborador;
    protected Integer cdRCTR;
    protected Integer cdZeroKm;
    protected String dtFinalExtPerimetro;
    protected String dtInicioExtPerimetro;
    protected String flCoberturaSP;
    protected String flDespesasExtraordinaria;
    protected String flExtensaoRCFReboque;
    protected String flExtensaoRCFVeiculo;
    protected String flRemoveCl67;
    protected Double isAppInvalidez;
    protected Double isAppMorte;
    protected Double isBlindagem;
    protected Double isCarroceria;
    protected Double isCasco;
    protected Double isDanosCorporais;
    protected Double isDanosMateriais;
    protected Double isDanosMorais;
    protected Double isEquipamentos;
    protected Double isGarantiaUnica;
    protected Double isKitGas;
    protected Integer nuDiasDiariaParalisacao;
    protected Integer nuDiasExtensaoPerimetro;
    protected Double vlDiariaParalisacao;

    /**
     * Gets the value of the cdClausulaAssistencia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdClausulaAssistencia() {
        return cdClausulaAssistencia;
    }

    /**
     * Sets the value of the cdClausulaAssistencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdClausulaAssistencia(Integer value) {
        this.cdClausulaAssistencia = value;
    }

    /**
     * Gets the value of the cdClausulaCarroReserva property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdClausulaCarroReserva() {
        return cdClausulaCarroReserva;
    }

    /**
     * Sets the value of the cdClausulaCarroReserva property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdClausulaCarroReserva(Integer value) {
        this.cdClausulaCarroReserva = value;
    }

    /**
     * Gets the value of the cdClausulaVidros property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdClausulaVidros() {
        return cdClausulaVidros;
    }

    /**
     * Sets the value of the cdClausulaVidros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdClausulaVidros(Integer value) {
        this.cdClausulaVidros = value;
    }

    /**
     * Gets the value of the cdExtensaoRCFColaborador property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdExtensaoRCFColaborador() {
        return cdExtensaoRCFColaborador;
    }

    /**
     * Sets the value of the cdExtensaoRCFColaborador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdExtensaoRCFColaborador(Integer value) {
        this.cdExtensaoRCFColaborador = value;
    }

    /**
     * Gets the value of the cdRCTR property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdRCTR() {
        return cdRCTR;
    }

    /**
     * Sets the value of the cdRCTR property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdRCTR(Integer value) {
        this.cdRCTR = value;
    }

    /**
     * Gets the value of the cdZeroKm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdZeroKm() {
        return cdZeroKm;
    }

    /**
     * Sets the value of the cdZeroKm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdZeroKm(Integer value) {
        this.cdZeroKm = value;
    }

    /**
     * Gets the value of the dtFinalExtPerimetro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFinalExtPerimetro() {
        return dtFinalExtPerimetro;
    }

    /**
     * Sets the value of the dtFinalExtPerimetro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFinalExtPerimetro(String value) {
        this.dtFinalExtPerimetro = value;
    }

    /**
     * Gets the value of the dtInicioExtPerimetro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioExtPerimetro() {
        return dtInicioExtPerimetro;
    }

    /**
     * Sets the value of the dtInicioExtPerimetro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioExtPerimetro(String value) {
        this.dtInicioExtPerimetro = value;
    }

    /**
     * Gets the value of the flCoberturaSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlCoberturaSP() {
        return flCoberturaSP;
    }

    /**
     * Sets the value of the flCoberturaSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlCoberturaSP(String value) {
        this.flCoberturaSP = value;
    }

    /**
     * Gets the value of the flDespesasExtraordinaria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlDespesasExtraordinaria() {
        return flDespesasExtraordinaria;
    }

    /**
     * Sets the value of the flDespesasExtraordinaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlDespesasExtraordinaria(String value) {
        this.flDespesasExtraordinaria = value;
    }

    /**
     * Gets the value of the flExtensaoRCFReboque property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlExtensaoRCFReboque() {
        return flExtensaoRCFReboque;
    }

    /**
     * Sets the value of the flExtensaoRCFReboque property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlExtensaoRCFReboque(String value) {
        this.flExtensaoRCFReboque = value;
    }

    /**
     * Gets the value of the flExtensaoRCFVeiculo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlExtensaoRCFVeiculo() {
        return flExtensaoRCFVeiculo;
    }

    /**
     * Sets the value of the flExtensaoRCFVeiculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlExtensaoRCFVeiculo(String value) {
        this.flExtensaoRCFVeiculo = value;
    }

    /**
     * Gets the value of the flRemoveCl67 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlRemoveCl67() {
        return flRemoveCl67;
    }

    /**
     * Sets the value of the flRemoveCl67 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlRemoveCl67(String value) {
        this.flRemoveCl67 = value;
    }

    /**
     * Gets the value of the isAppInvalidez property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsAppInvalidez() {
        return isAppInvalidez;
    }

    /**
     * Sets the value of the isAppInvalidez property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsAppInvalidez(Double value) {
        this.isAppInvalidez = value;
    }

    /**
     * Gets the value of the isAppMorte property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsAppMorte() {
        return isAppMorte;
    }

    /**
     * Sets the value of the isAppMorte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsAppMorte(Double value) {
        this.isAppMorte = value;
    }

    /**
     * Gets the value of the isBlindagem property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsBlindagem() {
        return isBlindagem;
    }

    /**
     * Sets the value of the isBlindagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsBlindagem(Double value) {
        this.isBlindagem = value;
    }

    /**
     * Gets the value of the isCarroceria property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsCarroceria() {
        return isCarroceria;
    }

    /**
     * Sets the value of the isCarroceria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsCarroceria(Double value) {
        this.isCarroceria = value;
    }

    /**
     * Gets the value of the isCasco property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsCasco() {
        return isCasco;
    }

    /**
     * Sets the value of the isCasco property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsCasco(Double value) {
        this.isCasco = value;
    }

    /**
     * Gets the value of the isDanosCorporais property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsDanosCorporais() {
        return isDanosCorporais;
    }

    /**
     * Sets the value of the isDanosCorporais property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsDanosCorporais(Double value) {
        this.isDanosCorporais = value;
    }

    /**
     * Gets the value of the isDanosMateriais property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsDanosMateriais() {
        return isDanosMateriais;
    }

    /**
     * Sets the value of the isDanosMateriais property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsDanosMateriais(Double value) {
        this.isDanosMateriais = value;
    }

    /**
     * Gets the value of the isDanosMorais property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsDanosMorais() {
        return isDanosMorais;
    }

    /**
     * Sets the value of the isDanosMorais property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsDanosMorais(Double value) {
        this.isDanosMorais = value;
    }

    /**
     * Gets the value of the isEquipamentos property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsEquipamentos() {
        return isEquipamentos;
    }

    /**
     * Sets the value of the isEquipamentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsEquipamentos(Double value) {
        this.isEquipamentos = value;
    }

    /**
     * Gets the value of the isGarantiaUnica property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsGarantiaUnica() {
        return isGarantiaUnica;
    }

    /**
     * Sets the value of the isGarantiaUnica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsGarantiaUnica(Double value) {
        this.isGarantiaUnica = value;
    }

    /**
     * Gets the value of the isKitGas property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIsKitGas() {
        return isKitGas;
    }

    /**
     * Sets the value of the isKitGas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIsKitGas(Double value) {
        this.isKitGas = value;
    }

    /**
     * Gets the value of the nuDiasDiariaParalisacao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDiasDiariaParalisacao() {
        return nuDiasDiariaParalisacao;
    }

    /**
     * Sets the value of the nuDiasDiariaParalisacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDiasDiariaParalisacao(Integer value) {
        this.nuDiasDiariaParalisacao = value;
    }

    /**
     * Gets the value of the nuDiasExtensaoPerimetro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDiasExtensaoPerimetro() {
        return nuDiasExtensaoPerimetro;
    }

    /**
     * Sets the value of the nuDiasExtensaoPerimetro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDiasExtensaoPerimetro(Integer value) {
        this.nuDiasExtensaoPerimetro = value;
    }

    /**
     * Gets the value of the vlDiariaParalisacao property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlDiariaParalisacao() {
        return vlDiariaParalisacao;
    }

    /**
     * Sets the value of the vlDiariaParalisacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlDiariaParalisacao(Double value) {
        this.vlDiariaParalisacao = value;
    }

}
