//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EImpactoAlertaVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EImpactoAlertaVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdEspecieSeguro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdModalidadeSeguro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listaAlertas" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfAlertaVo" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EImpactoAlertaVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdEspecieSeguro",
    "cdModalidadeSeguro",
    "dtInicioVigencia",
    "listaAlertas",
    "nuCpfCnpjCorretor"
})
public class EImpactoAlertaVo {

    protected Integer cdEspecieSeguro;
    protected Integer cdModalidadeSeguro;
    protected String dtInicioVigencia;
    protected ArrayOfAlertaVo listaAlertas;
    protected String nuCpfCnpjCorretor;

    /**
     * Gets the value of the cdEspecieSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEspecieSeguro() {
        return cdEspecieSeguro;
    }

    /**
     * Sets the value of the cdEspecieSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEspecieSeguro(Integer value) {
        this.cdEspecieSeguro = value;
    }

    /**
     * Gets the value of the cdModalidadeSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdModalidadeSeguro() {
        return cdModalidadeSeguro;
    }

    /**
     * Sets the value of the cdModalidadeSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdModalidadeSeguro(Integer value) {
        this.cdModalidadeSeguro = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the listaAlertas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAlertaVo }
     *     
     */
    public ArrayOfAlertaVo getListaAlertas() {
        return listaAlertas;
    }

    /**
     * Sets the value of the listaAlertas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAlertaVo }
     *     
     */
    public void setListaAlertas(ArrayOfAlertaVo value) {
        this.listaAlertas = value;
    }

    /**
     * Gets the value of the nuCpfCnpjCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjCorretor() {
        return nuCpfCnpjCorretor;
    }

    /**
     * Sets the value of the nuCpfCnpjCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjCorretor(String value) {
        this.nuCpfCnpjCorretor = value;
    }

}
