//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnderecoCotacaoEndossoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnderecoCotacaoEndossoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdCEP" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoEndereco" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoLogradouro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdUF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsComplemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmBairro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmLogradouro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmMunicipio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuLogradouro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnderecoCotacaoEndossoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdCEP",
    "cdTipoEndereco",
    "cdTipoLogradouro",
    "cdUF",
    "dsComplemento",
    "nmBairro",
    "nmLogradouro",
    "nmMunicipio",
    "nuLogradouro"
})
public class EnderecoCotacaoEndossoVo {

    protected Integer cdCEP;
    protected Integer cdTipoEndereco;
    protected Integer cdTipoLogradouro;
    protected String cdUF;
    protected String dsComplemento;
    protected String nmBairro;
    protected String nmLogradouro;
    protected String nmMunicipio;
    protected Integer nuLogradouro;

    /**
     * Gets the value of the cdCEP property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdCEP() {
        return cdCEP;
    }

    /**
     * Sets the value of the cdCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdCEP(Integer value) {
        this.cdCEP = value;
    }

    /**
     * Gets the value of the cdTipoEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoEndereco() {
        return cdTipoEndereco;
    }

    /**
     * Sets the value of the cdTipoEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoEndereco(Integer value) {
        this.cdTipoEndereco = value;
    }

    /**
     * Gets the value of the cdTipoLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoLogradouro() {
        return cdTipoLogradouro;
    }

    /**
     * Sets the value of the cdTipoLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoLogradouro(Integer value) {
        this.cdTipoLogradouro = value;
    }

    /**
     * Gets the value of the cdUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdUF() {
        return cdUF;
    }

    /**
     * Sets the value of the cdUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdUF(String value) {
        this.cdUF = value;
    }

    /**
     * Gets the value of the dsComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsComplemento() {
        return dsComplemento;
    }

    /**
     * Sets the value of the dsComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsComplemento(String value) {
        this.dsComplemento = value;
    }

    /**
     * Gets the value of the nmBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmBairro() {
        return nmBairro;
    }

    /**
     * Sets the value of the nmBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmBairro(String value) {
        this.nmBairro = value;
    }

    /**
     * Gets the value of the nmLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmLogradouro() {
        return nmLogradouro;
    }

    /**
     * Sets the value of the nmLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmLogradouro(String value) {
        this.nmLogradouro = value;
    }

    /**
     * Gets the value of the nmMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmMunicipio() {
        return nmMunicipio;
    }

    /**
     * Sets the value of the nmMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmMunicipio(String value) {
        this.nmMunicipio = value;
    }

    /**
     * Gets the value of the nuLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuLogradouro() {
        return nuLogradouro;
    }

    /**
     * Sets the value of the nuLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuLogradouro(Integer value) {
        this.nuLogradouro = value;
    }

}
