//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnderecoApoliceVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnderecoApoliceVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdTipoEndereco" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoLogadouro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdUF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsComplemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmBairro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmLogadouro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmMunicipio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCep" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuLogadouro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnderecoApoliceVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdTipoEndereco",
    "cdTipoLogadouro",
    "cdUF",
    "dsComplemento",
    "nmBairro",
    "nmLogadouro",
    "nmMunicipio",
    "nuCep",
    "nuLogadouro"
})
public class EnderecoApoliceVo {

    protected Integer cdTipoEndereco;
    protected Integer cdTipoLogadouro;
    protected String cdUF;
    protected String dsComplemento;
    protected String nmBairro;
    protected String nmLogadouro;
    protected String nmMunicipio;
    protected String nuCep;
    protected Integer nuLogadouro;

    /**
     * Gets the value of the cdTipoEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoEndereco() {
        return cdTipoEndereco;
    }

    /**
     * Sets the value of the cdTipoEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoEndereco(Integer value) {
        this.cdTipoEndereco = value;
    }

    /**
     * Gets the value of the cdTipoLogadouro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoLogadouro() {
        return cdTipoLogadouro;
    }

    /**
     * Sets the value of the cdTipoLogadouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoLogadouro(Integer value) {
        this.cdTipoLogadouro = value;
    }

    /**
     * Gets the value of the cdUF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdUF() {
        return cdUF;
    }

    /**
     * Sets the value of the cdUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdUF(String value) {
        this.cdUF = value;
    }

    /**
     * Gets the value of the dsComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsComplemento() {
        return dsComplemento;
    }

    /**
     * Sets the value of the dsComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsComplemento(String value) {
        this.dsComplemento = value;
    }

    /**
     * Gets the value of the nmBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmBairro() {
        return nmBairro;
    }

    /**
     * Sets the value of the nmBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmBairro(String value) {
        this.nmBairro = value;
    }

    /**
     * Gets the value of the nmLogadouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmLogadouro() {
        return nmLogadouro;
    }

    /**
     * Sets the value of the nmLogadouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmLogadouro(String value) {
        this.nmLogadouro = value;
    }

    /**
     * Gets the value of the nmMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmMunicipio() {
        return nmMunicipio;
    }

    /**
     * Sets the value of the nmMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmMunicipio(String value) {
        this.nmMunicipio = value;
    }

    /**
     * Gets the value of the nuCep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCep() {
        return nuCep;
    }

    /**
     * Sets the value of the nuCep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCep(String value) {
        this.nuCep = value;
    }

    /**
     * Gets the value of the nuLogadouro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuLogadouro() {
        return nuLogadouro;
    }

    /**
     * Sets the value of the nuLogadouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuLogadouro(Integer value) {
        this.nuLogadouro = value;
    }

}
