//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EPagamentoEndossoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EPagamentoEndossoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdOpcaoPagtoDemais" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdOpcaoPagtoPrim" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDiaVencimento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuParcelas" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="vlAdicionalFinal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="vlDemaisParcelas" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="vlFatorJuros" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="vlIofFinal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="vlPrimeiraParcela" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPagamentoEndossoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdOpcaoPagtoDemais",
    "cdOpcaoPagtoPrim",
    "nuDiaVencimento",
    "nuParcelas",
    "vlAdicionalFinal",
    "vlDemaisParcelas",
    "vlFatorJuros",
    "vlIofFinal",
    "vlPrimeiraParcela"
})
public class EPagamentoEndossoVo {

    protected Integer cdOpcaoPagtoDemais;
    protected Integer cdOpcaoPagtoPrim;
    protected Integer nuDiaVencimento;
    protected Integer nuParcelas;
    protected Double vlAdicionalFinal;
    protected Double vlDemaisParcelas;
    protected Double vlFatorJuros;
    protected Double vlIofFinal;
    protected Double vlPrimeiraParcela;

    /**
     * Gets the value of the cdOpcaoPagtoDemais property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdOpcaoPagtoDemais() {
        return cdOpcaoPagtoDemais;
    }

    /**
     * Sets the value of the cdOpcaoPagtoDemais property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdOpcaoPagtoDemais(Integer value) {
        this.cdOpcaoPagtoDemais = value;
    }

    /**
     * Gets the value of the cdOpcaoPagtoPrim property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdOpcaoPagtoPrim() {
        return cdOpcaoPagtoPrim;
    }

    /**
     * Sets the value of the cdOpcaoPagtoPrim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdOpcaoPagtoPrim(Integer value) {
        this.cdOpcaoPagtoPrim = value;
    }

    /**
     * Gets the value of the nuDiaVencimento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDiaVencimento() {
        return nuDiaVencimento;
    }

    /**
     * Sets the value of the nuDiaVencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDiaVencimento(Integer value) {
        this.nuDiaVencimento = value;
    }

    /**
     * Gets the value of the nuParcelas property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuParcelas() {
        return nuParcelas;
    }

    /**
     * Sets the value of the nuParcelas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuParcelas(Integer value) {
        this.nuParcelas = value;
    }

    /**
     * Gets the value of the vlAdicionalFinal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlAdicionalFinal() {
        return vlAdicionalFinal;
    }

    /**
     * Sets the value of the vlAdicionalFinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlAdicionalFinal(Double value) {
        this.vlAdicionalFinal = value;
    }

    /**
     * Gets the value of the vlDemaisParcelas property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlDemaisParcelas() {
        return vlDemaisParcelas;
    }

    /**
     * Sets the value of the vlDemaisParcelas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlDemaisParcelas(Double value) {
        this.vlDemaisParcelas = value;
    }

    /**
     * Gets the value of the vlFatorJuros property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlFatorJuros() {
        return vlFatorJuros;
    }

    /**
     * Sets the value of the vlFatorJuros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlFatorJuros(Double value) {
        this.vlFatorJuros = value;
    }

    /**
     * Gets the value of the vlIofFinal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlIofFinal() {
        return vlIofFinal;
    }

    /**
     * Sets the value of the vlIofFinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlIofFinal(Double value) {
        this.vlIofFinal = value;
    }

    /**
     * Gets the value of the vlPrimeiraParcela property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlPrimeiraParcela() {
        return vlPrimeiraParcela;
    }

    /**
     * Sets the value of the vlPrimeiraParcela property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlPrimeiraParcela(Double value) {
        this.vlPrimeiraParcela = value;
    }

}
