//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipamentoImpressaoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipamentoImpressaoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdEquipamento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dsEquipamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vlEquipamento" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipamentoImpressaoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdEquipamento",
    "dsEquipamento",
    "vlEquipamento"
})
public class EquipamentoImpressaoVo {

    protected Integer cdEquipamento;
    protected String dsEquipamento;
    protected Double vlEquipamento;

    /**
     * Gets the value of the cdEquipamento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEquipamento() {
        return cdEquipamento;
    }

    /**
     * Sets the value of the cdEquipamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEquipamento(Integer value) {
        this.cdEquipamento = value;
    }

    /**
     * Gets the value of the dsEquipamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsEquipamento() {
        return dsEquipamento;
    }

    /**
     * Sets the value of the dsEquipamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsEquipamento(String value) {
        this.dsEquipamento = value;
    }

    /**
     * Gets the value of the vlEquipamento property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVlEquipamento() {
        return vlEquipamento;
    }

    /**
     * Sets the value of the vlEquipamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVlEquipamento(Double value) {
        this.vlEquipamento = value;
    }

}
