//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ETelefoneEndossoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ETelefoneEndossoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdTipoTelefone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuDDD" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuRamal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nuTelefone" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETelefoneEndossoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdTipoTelefone",
    "nuDDD",
    "nuRamal",
    "nuTelefone"
})
public class ETelefoneEndossoVo {

    protected Integer cdTipoTelefone;
    protected Integer nuDDD;
    protected Integer nuRamal;
    protected Integer nuTelefone;

    /**
     * Gets the value of the cdTipoTelefone property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoTelefone() {
        return cdTipoTelefone;
    }

    /**
     * Sets the value of the cdTipoTelefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoTelefone(Integer value) {
        this.cdTipoTelefone = value;
    }

    /**
     * Gets the value of the nuDDD property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuDDD() {
        return nuDDD;
    }

    /**
     * Sets the value of the nuDDD property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuDDD(Integer value) {
        this.nuDDD = value;
    }

    /**
     * Gets the value of the nuRamal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuRamal() {
        return nuRamal;
    }

    /**
     * Sets the value of the nuRamal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuRamal(Integer value) {
        this.nuRamal = value;
    }

    /**
     * Gets the value of the nuTelefone property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNuTelefone() {
        return nuTelefone;
    }

    /**
     * Sets the value of the nuTelefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNuTelefone(Integer value) {
        this.nuTelefone = value;
    }

}
