//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GrupoCoberturaVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrupoCoberturaVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdGrupoCobertura" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dsCategoria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsGrupoCobertura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcAgravamento" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcBonus" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoCorretor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcComissaoPlataforma" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="pcDescontoSegurado" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrupoCoberturaVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdGrupoCobertura",
    "dsCategoria",
    "dsGrupoCobertura",
    "pcAgravamento",
    "pcBonus",
    "pcComissaoCorretor",
    "pcComissaoPlataforma",
    "pcDescontoSegurado"
})
public class GrupoCoberturaVo {

    protected Integer cdGrupoCobertura;
    protected String dsCategoria;
    protected String dsGrupoCobertura;
    protected Double pcAgravamento;
    protected Double pcBonus;
    protected Double pcComissaoCorretor;
    protected Double pcComissaoPlataforma;
    protected Double pcDescontoSegurado;

    /**
     * Gets the value of the cdGrupoCobertura property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdGrupoCobertura() {
        return cdGrupoCobertura;
    }

    /**
     * Sets the value of the cdGrupoCobertura property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdGrupoCobertura(Integer value) {
        this.cdGrupoCobertura = value;
    }

    /**
     * Gets the value of the dsCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsCategoria() {
        return dsCategoria;
    }

    /**
     * Sets the value of the dsCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsCategoria(String value) {
        this.dsCategoria = value;
    }

    /**
     * Gets the value of the dsGrupoCobertura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsGrupoCobertura() {
        return dsGrupoCobertura;
    }

    /**
     * Sets the value of the dsGrupoCobertura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsGrupoCobertura(String value) {
        this.dsGrupoCobertura = value;
    }

    /**
     * Gets the value of the pcAgravamento property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcAgravamento() {
        return pcAgravamento;
    }

    /**
     * Sets the value of the pcAgravamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcAgravamento(Double value) {
        this.pcAgravamento = value;
    }

    /**
     * Gets the value of the pcBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcBonus() {
        return pcBonus;
    }

    /**
     * Sets the value of the pcBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcBonus(Double value) {
        this.pcBonus = value;
    }

    /**
     * Gets the value of the pcComissaoCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoCorretor() {
        return pcComissaoCorretor;
    }

    /**
     * Sets the value of the pcComissaoCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoCorretor(Double value) {
        this.pcComissaoCorretor = value;
    }

    /**
     * Gets the value of the pcComissaoPlataforma property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcComissaoPlataforma() {
        return pcComissaoPlataforma;
    }

    /**
     * Sets the value of the pcComissaoPlataforma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcComissaoPlataforma(Double value) {
        this.pcComissaoPlataforma = value;
    }

    /**
     * Gets the value of the pcDescontoSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPcDescontoSegurado() {
        return pcDescontoSegurado;
    }

    /**
     * Sets the value of the pcDescontoSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPcDescontoSegurado(Double value) {
        this.pcDescontoSegurado = value;
    }

}
