//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoricoPropostaVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoricoPropostaVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdEvento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdPropostaAtual" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="cdUsuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dsEvento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtEfetivacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtEvento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoricoPropostaVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdEvento",
    "cdPropostaAtual",
    "cdUsuario",
    "dsEvento",
    "dtEfetivacao",
    "dtEvento"
})
public class HistoricoPropostaVo {

    protected Integer cdEvento;
    protected Long cdPropostaAtual;
    protected String cdUsuario;
    protected String dsEvento;
    protected String dtEfetivacao;
    protected String dtEvento;

    /**
     * Gets the value of the cdEvento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEvento() {
        return cdEvento;
    }

    /**
     * Sets the value of the cdEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEvento(Integer value) {
        this.cdEvento = value;
    }

    /**
     * Gets the value of the cdPropostaAtual property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdPropostaAtual() {
        return cdPropostaAtual;
    }

    /**
     * Sets the value of the cdPropostaAtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdPropostaAtual(Long value) {
        this.cdPropostaAtual = value;
    }

    /**
     * Gets the value of the cdUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdUsuario() {
        return cdUsuario;
    }

    /**
     * Sets the value of the cdUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdUsuario(String value) {
        this.cdUsuario = value;
    }

    /**
     * Gets the value of the dsEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsEvento() {
        return dsEvento;
    }

    /**
     * Sets the value of the dsEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsEvento(String value) {
        this.dsEvento = value;
    }

    /**
     * Gets the value of the dtEfetivacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEfetivacao() {
        return dtEfetivacao;
    }

    /**
     * Sets the value of the dtEfetivacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEfetivacao(String value) {
        this.dtEfetivacao = value;
    }

    /**
     * Gets the value of the dtEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEvento() {
        return dtEvento;
    }

    /**
     * Sets the value of the dtEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEvento(String value) {
        this.dtEvento = value;
    }

}
