//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImpressaoPropostaVoOut complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImpressaoPropostaVoOut">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bytesPDF" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="mensagemErroVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}MensagemErroVo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImpressaoPropostaVoOut", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "bytesPDF",
    "mensagemErroVo"
})
public class ImpressaoPropostaVoOut {

    protected byte[] bytesPDF;
    protected MensagemErroVo mensagemErroVo;

    /**
     * Gets the value of the bytesPDF property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBytesPDF() {
        return bytesPDF;
    }

    /**
     * Sets the value of the bytesPDF property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBytesPDF(byte[] value) {
        this.bytesPDF = ((byte[]) value);
    }

    /**
     * Gets the value of the mensagemErroVo property.
     * 
     * @return
     *     possible object is
     *     {@link MensagemErroVo }
     *     
     */
    public MensagemErroVo getMensagemErroVo() {
        return mensagemErroVo;
    }

    /**
     * Sets the value of the mensagemErroVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MensagemErroVo }
     *     
     */
    public void setMensagemErroVo(MensagemErroVo value) {
        this.mensagemErroVo = value;
    }

}
