//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParametroApoliceVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParametroApoliceVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdCorretor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoPessoaCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flAdicionalFracionamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flCcb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flCustoApolice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flIOF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flPessoaCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flProRata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuVersaoDLL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParametroApoliceVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdCorretor",
    "cdTipoPessoaCorretor",
    "flAdicionalFracionamento",
    "flCcb",
    "flCustoApolice",
    "flIOF",
    "flPessoaCorretor",
    "flProRata",
    "nuCpfCnpjCorretor",
    "nuCpfCnpjProponente",
    "nuVersaoDLL"
})
public class ParametroApoliceVo {

    protected Integer cdCorretor;
    protected String cdTipoPessoaCorretor;
    protected String flAdicionalFracionamento;
    protected String flCcb;
    protected String flCustoApolice;
    protected String flIOF;
    protected String flPessoaCorretor;
    protected String flProRata;
    protected String nuCpfCnpjCorretor;
    protected String nuCpfCnpjProponente;
    protected String nuVersaoDLL;

    /**
     * Gets the value of the cdCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdCorretor() {
        return cdCorretor;
    }

    /**
     * Sets the value of the cdCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdCorretor(Integer value) {
        this.cdCorretor = value;
    }

    /**
     * Gets the value of the cdTipoPessoaCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdTipoPessoaCorretor() {
        return cdTipoPessoaCorretor;
    }

    /**
     * Sets the value of the cdTipoPessoaCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdTipoPessoaCorretor(String value) {
        this.cdTipoPessoaCorretor = value;
    }

    /**
     * Gets the value of the flAdicionalFracionamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAdicionalFracionamento() {
        return flAdicionalFracionamento;
    }

    /**
     * Sets the value of the flAdicionalFracionamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAdicionalFracionamento(String value) {
        this.flAdicionalFracionamento = value;
    }

    /**
     * Gets the value of the flCcb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlCcb() {
        return flCcb;
    }

    /**
     * Sets the value of the flCcb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlCcb(String value) {
        this.flCcb = value;
    }

    /**
     * Gets the value of the flCustoApolice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlCustoApolice() {
        return flCustoApolice;
    }

    /**
     * Sets the value of the flCustoApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlCustoApolice(String value) {
        this.flCustoApolice = value;
    }

    /**
     * Gets the value of the flIOF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlIOF() {
        return flIOF;
    }

    /**
     * Sets the value of the flIOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlIOF(String value) {
        this.flIOF = value;
    }

    /**
     * Gets the value of the flPessoaCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlPessoaCorretor() {
        return flPessoaCorretor;
    }

    /**
     * Sets the value of the flPessoaCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlPessoaCorretor(String value) {
        this.flPessoaCorretor = value;
    }

    /**
     * Gets the value of the flProRata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlProRata() {
        return flProRata;
    }

    /**
     * Sets the value of the flProRata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlProRata(String value) {
        this.flProRata = value;
    }

    /**
     * Gets the value of the nuCpfCnpjCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjCorretor() {
        return nuCpfCnpjCorretor;
    }

    /**
     * Sets the value of the nuCpfCnpjCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjCorretor(String value) {
        this.nuCpfCnpjCorretor = value;
    }

    /**
     * Gets the value of the nuCpfCnpjProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuCpfCnpjProponente() {
        return nuCpfCnpjProponente;
    }

    /**
     * Sets the value of the nuCpfCnpjProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuCpfCnpjProponente(String value) {
        this.nuCpfCnpjProponente = value;
    }

    /**
     * Gets the value of the nuVersaoDLL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuVersaoDLL() {
        return nuVersaoDLL;
    }

    /**
     * Sets the value of the nuVersaoDLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuVersaoDLL(String value) {
        this.nuVersaoDLL = value;
    }

}
