//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParametroImpressaoVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParametroImpressaoVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdCorretor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdCpfCnpjCorretor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="flAdicionalFracionamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flCustoApolice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flIOF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flProRata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flTipoPessoaCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nmCorretor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuVersaoDLL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParametroImpressaoVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdCorretor",
    "cdCpfCnpjCorretor",
    "flAdicionalFracionamento",
    "flCustoApolice",
    "flIOF",
    "flProRata",
    "flTipoPessoaCorretor",
    "nmCorretor",
    "nuVersaoDLL"
})
public class ParametroImpressaoVo {

    protected Integer cdCorretor;
    protected Long cdCpfCnpjCorretor;
    protected String flAdicionalFracionamento;
    protected String flCustoApolice;
    protected String flIOF;
    protected String flProRata;
    protected String flTipoPessoaCorretor;
    protected String nmCorretor;
    protected String nuVersaoDLL;

    /**
     * Gets the value of the cdCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdCorretor() {
        return cdCorretor;
    }

    /**
     * Sets the value of the cdCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdCorretor(Integer value) {
        this.cdCorretor = value;
    }

    /**
     * Gets the value of the cdCpfCnpjCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdCpfCnpjCorretor() {
        return cdCpfCnpjCorretor;
    }

    /**
     * Sets the value of the cdCpfCnpjCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdCpfCnpjCorretor(Long value) {
        this.cdCpfCnpjCorretor = value;
    }

    /**
     * Gets the value of the flAdicionalFracionamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlAdicionalFracionamento() {
        return flAdicionalFracionamento;
    }

    /**
     * Sets the value of the flAdicionalFracionamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlAdicionalFracionamento(String value) {
        this.flAdicionalFracionamento = value;
    }

    /**
     * Gets the value of the flCustoApolice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlCustoApolice() {
        return flCustoApolice;
    }

    /**
     * Sets the value of the flCustoApolice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlCustoApolice(String value) {
        this.flCustoApolice = value;
    }

    /**
     * Gets the value of the flIOF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlIOF() {
        return flIOF;
    }

    /**
     * Sets the value of the flIOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlIOF(String value) {
        this.flIOF = value;
    }

    /**
     * Gets the value of the flProRata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlProRata() {
        return flProRata;
    }

    /**
     * Sets the value of the flProRata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlProRata(String value) {
        this.flProRata = value;
    }

    /**
     * Gets the value of the flTipoPessoaCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlTipoPessoaCorretor() {
        return flTipoPessoaCorretor;
    }

    /**
     * Sets the value of the flTipoPessoaCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlTipoPessoaCorretor(String value) {
        this.flTipoPessoaCorretor = value;
    }

    /**
     * Gets the value of the nmCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmCorretor() {
        return nmCorretor;
    }

    /**
     * Sets the value of the nmCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmCorretor(String value) {
        this.nmCorretor = value;
    }

    /**
     * Gets the value of the nuVersaoDLL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuVersaoDLL() {
        return nuVersaoDLL;
    }

    /**
     * Sets the value of the nuVersaoDLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuVersaoDLL(String value) {
        this.nuVersaoDLL = value;
    }

}
