//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropostaIncompletaVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropostaIncompletaVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdCia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdCorretor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="dtFimVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dvChassi" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="indVeiculoZero" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listaAlertas" type="{http://vo.model.calculoauto.paol.bradseg.com.br}ArrayOfMensagemAlertaVo" minOccurs="0"/>
 *         &lt;element name="mensagemErroVo" type="{http://vo.model.calculoauto.paol.bradseg.com.br}MensagemErroVo" minOccurs="0"/>
 *         &lt;element name="nmProponente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuChassi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nuCpfCnpjCorretor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="nuPropostaIncompleta" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="placa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="qtdItemHist" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tpPessoa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tpSeguro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ultEvento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropostaIncompletaVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdCia",
    "cdCorretor",
    "dtFimVigencia",
    "dtInicioVigencia",
    "dvChassi",
    "indVeiculoZero",
    "listaAlertas",
    "mensagemErroVo",
    "nmProponente",
    "nuChassi",
    "nuCpfCnpjCorretor",
    "nuPropostaIncompleta",
    "placa",
    "qtdItemHist",
    "tpPessoa",
    "tpSeguro",
    "ultEvento"
})
public class PropostaIncompletaVo {

    protected Integer cdCia;
    protected Long cdCorretor;
    protected String dtFimVigencia;
    protected String dtInicioVigencia;
    protected Integer dvChassi;
    protected String indVeiculoZero;
    protected ArrayOfMensagemAlertaVo listaAlertas;
    protected MensagemErroVo mensagemErroVo;
    protected String nmProponente;
    protected String nuChassi;
    protected Long nuCpfCnpjCorretor;
    protected Long nuPropostaIncompleta;
    protected String placa;
    protected Integer qtdItemHist;
    protected String tpPessoa;
    protected String tpSeguro;
    protected Integer ultEvento;

    /**
     * Gets the value of the cdCia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdCia() {
        return cdCia;
    }

    /**
     * Sets the value of the cdCia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdCia(Integer value) {
        this.cdCia = value;
    }

    /**
     * Gets the value of the cdCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCdCorretor() {
        return cdCorretor;
    }

    /**
     * Sets the value of the cdCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCdCorretor(Long value) {
        this.cdCorretor = value;
    }

    /**
     * Gets the value of the dtFimVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtFimVigencia() {
        return dtFimVigencia;
    }

    /**
     * Sets the value of the dtFimVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtFimVigencia(String value) {
        this.dtFimVigencia = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the dvChassi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDvChassi() {
        return dvChassi;
    }

    /**
     * Sets the value of the dvChassi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDvChassi(Integer value) {
        this.dvChassi = value;
    }

    /**
     * Gets the value of the indVeiculoZero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndVeiculoZero() {
        return indVeiculoZero;
    }

    /**
     * Sets the value of the indVeiculoZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndVeiculoZero(String value) {
        this.indVeiculoZero = value;
    }

    /**
     * Gets the value of the listaAlertas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMensagemAlertaVo }
     *     
     */
    public ArrayOfMensagemAlertaVo getListaAlertas() {
        return listaAlertas;
    }

    /**
     * Sets the value of the listaAlertas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMensagemAlertaVo }
     *     
     */
    public void setListaAlertas(ArrayOfMensagemAlertaVo value) {
        this.listaAlertas = value;
    }

    /**
     * Gets the value of the mensagemErroVo property.
     * 
     * @return
     *     possible object is
     *     {@link MensagemErroVo }
     *     
     */
    public MensagemErroVo getMensagemErroVo() {
        return mensagemErroVo;
    }

    /**
     * Sets the value of the mensagemErroVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MensagemErroVo }
     *     
     */
    public void setMensagemErroVo(MensagemErroVo value) {
        this.mensagemErroVo = value;
    }

    /**
     * Gets the value of the nmProponente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmProponente() {
        return nmProponente;
    }

    /**
     * Sets the value of the nmProponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmProponente(String value) {
        this.nmProponente = value;
    }

    /**
     * Gets the value of the nuChassi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuChassi() {
        return nuChassi;
    }

    /**
     * Sets the value of the nuChassi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuChassi(String value) {
        this.nuChassi = value;
    }

    /**
     * Gets the value of the nuCpfCnpjCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNuCpfCnpjCorretor() {
        return nuCpfCnpjCorretor;
    }

    /**
     * Sets the value of the nuCpfCnpjCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNuCpfCnpjCorretor(Long value) {
        this.nuCpfCnpjCorretor = value;
    }

    /**
     * Gets the value of the nuPropostaIncompleta property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNuPropostaIncompleta() {
        return nuPropostaIncompleta;
    }

    /**
     * Sets the value of the nuPropostaIncompleta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNuPropostaIncompleta(Long value) {
        this.nuPropostaIncompleta = value;
    }

    /**
     * Gets the value of the placa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaca() {
        return placa;
    }

    /**
     * Sets the value of the placa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaca(String value) {
        this.placa = value;
    }

    /**
     * Gets the value of the qtdItemHist property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQtdItemHist() {
        return qtdItemHist;
    }

    /**
     * Sets the value of the qtdItemHist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQtdItemHist(Integer value) {
        this.qtdItemHist = value;
    }

    /**
     * Gets the value of the tpPessoa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpPessoa() {
        return tpPessoa;
    }

    /**
     * Sets the value of the tpPessoa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpPessoa(String value) {
        this.tpPessoa = value;
    }

    /**
     * Gets the value of the tpSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpSeguro() {
        return tpSeguro;
    }

    /**
     * Sets the value of the tpSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpSeguro(String value) {
        this.tpSeguro = value;
    }

    /**
     * Gets the value of the ultEvento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUltEvento() {
        return ultEvento;
    }

    /**
     * Sets the value of the ultEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUltEvento(Integer value) {
        this.ultEvento = value;
    }

}
