//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValorAutoResidencialVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValorAutoResidencialVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdOpcao" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lmiPerdaPagamento" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lmiRCFamiliar" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lmiRE" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="lmiVendaval" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="valorAssistenciaResidencial" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="valorCapitalizacao" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValorAutoResidencialVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdOpcao",
    "lmiPerdaPagamento",
    "lmiRCFamiliar",
    "lmiRE",
    "lmiVendaval",
    "valorAssistenciaResidencial",
    "valorCapitalizacao"
})
public class ValorAutoResidencialVo {

    protected Integer cdOpcao;
    protected Double lmiPerdaPagamento;
    protected Double lmiRCFamiliar;
    protected Double lmiRE;
    protected Double lmiVendaval;
    protected Double valorAssistenciaResidencial;
    protected Double valorCapitalizacao;

    /**
     * Gets the value of the cdOpcao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdOpcao() {
        return cdOpcao;
    }

    /**
     * Sets the value of the cdOpcao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdOpcao(Integer value) {
        this.cdOpcao = value;
    }

    /**
     * Gets the value of the lmiPerdaPagamento property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLmiPerdaPagamento() {
        return lmiPerdaPagamento;
    }

    /**
     * Sets the value of the lmiPerdaPagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLmiPerdaPagamento(Double value) {
        this.lmiPerdaPagamento = value;
    }

    /**
     * Gets the value of the lmiRCFamiliar property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLmiRCFamiliar() {
        return lmiRCFamiliar;
    }

    /**
     * Sets the value of the lmiRCFamiliar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLmiRCFamiliar(Double value) {
        this.lmiRCFamiliar = value;
    }

    /**
     * Gets the value of the lmiRE property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLmiRE() {
        return lmiRE;
    }

    /**
     * Sets the value of the lmiRE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLmiRE(Double value) {
        this.lmiRE = value;
    }

    /**
     * Gets the value of the lmiVendaval property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLmiVendaval() {
        return lmiVendaval;
    }

    /**
     * Sets the value of the lmiVendaval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLmiVendaval(Double value) {
        this.lmiVendaval = value;
    }

    /**
     * Gets the value of the valorAssistenciaResidencial property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValorAssistenciaResidencial() {
        return valorAssistenciaResidencial;
    }

    /**
     * Sets the value of the valorAssistenciaResidencial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValorAssistenciaResidencial(Double value) {
        this.valorAssistenciaResidencial = value;
    }

    /**
     * Gets the value of the valorCapitalizacao property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValorCapitalizacao() {
        return valorCapitalizacao;
    }

    /**
     * Sets the value of the valorCapitalizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValorCapitalizacao(Double value) {
        this.valorCapitalizacao = value;
    }

}
