//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VeiculoCalculoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VeiculoCalculoVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anoCorrente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="anoModelo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codCPDCorretor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codEspecieSeguro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codSucursal" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="codTeleEmpresa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dtSaidaConcessionaria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="grupoVeiculo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="indicativoZeroKm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VeiculoCalculoVO", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "anoCorrente",
    "anoModelo",
    "codCPDCorretor",
    "codEspecieSeguro",
    "codSucursal",
    "codTeleEmpresa",
    "dtInicioVigencia",
    "dtSaidaConcessionaria",
    "grupoVeiculo",
    "indicativoZeroKm"
})
public class VeiculoCalculoVO {

    protected Integer anoCorrente;
    protected Integer anoModelo;
    protected Integer codCPDCorretor;
    protected Integer codEspecieSeguro;
    protected Integer codSucursal;
    protected Integer codTeleEmpresa;
    protected String dtInicioVigencia;
    protected String dtSaidaConcessionaria;
    protected Integer grupoVeiculo;
    protected String indicativoZeroKm;

    /**
     * Gets the value of the anoCorrente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnoCorrente() {
        return anoCorrente;
    }

    /**
     * Sets the value of the anoCorrente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAnoCorrente(Integer value) {
        this.anoCorrente = value;
    }

    /**
     * Gets the value of the anoModelo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnoModelo() {
        return anoModelo;
    }

    /**
     * Sets the value of the anoModelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAnoModelo(Integer value) {
        this.anoModelo = value;
    }

    /**
     * Gets the value of the codCPDCorretor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodCPDCorretor() {
        return codCPDCorretor;
    }

    /**
     * Sets the value of the codCPDCorretor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodCPDCorretor(Integer value) {
        this.codCPDCorretor = value;
    }

    /**
     * Gets the value of the codEspecieSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodEspecieSeguro() {
        return codEspecieSeguro;
    }

    /**
     * Sets the value of the codEspecieSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodEspecieSeguro(Integer value) {
        this.codEspecieSeguro = value;
    }

    /**
     * Gets the value of the codSucursal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodSucursal() {
        return codSucursal;
    }

    /**
     * Sets the value of the codSucursal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodSucursal(Integer value) {
        this.codSucursal = value;
    }

    /**
     * Gets the value of the codTeleEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodTeleEmpresa() {
        return codTeleEmpresa;
    }

    /**
     * Sets the value of the codTeleEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodTeleEmpresa(Integer value) {
        this.codTeleEmpresa = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the dtSaidaConcessionaria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtSaidaConcessionaria() {
        return dtSaidaConcessionaria;
    }

    /**
     * Sets the value of the dtSaidaConcessionaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtSaidaConcessionaria(String value) {
        this.dtSaidaConcessionaria = value;
    }

    /**
     * Gets the value of the grupoVeiculo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrupoVeiculo() {
        return grupoVeiculo;
    }

    /**
     * Sets the value of the grupoVeiculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrupoVeiculo(Integer value) {
        this.grupoVeiculo = value;
    }

    /**
     * Gets the value of the indicativoZeroKm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicativoZeroKm() {
        return indicativoZeroKm;
    }

    /**
     * Sets the value of the indicativoZeroKm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicativoZeroKm(String value) {
        this.indicativoZeroKm = value;
    }

}
