//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package br.com.bradseg.paol.calculoauto.model.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerificaAutoFlexVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerificaAutoFlexVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdEmpresa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoSeguro" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cdTipoVeiculo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dtInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flNovaTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerificaAutoFlexVo", namespace = "http://vo.model.calculoauto.paol.bradseg.com.br", propOrder = {
    "cdEmpresa",
    "cdTipoSeguro",
    "cdTipoVeiculo",
    "dtInicioVigencia",
    "flNovaTarifa"
})
public class VerificaAutoFlexVo {

    protected Integer cdEmpresa;
    protected Integer cdTipoSeguro;
    protected Integer cdTipoVeiculo;
    protected String dtInicioVigencia;
    protected String flNovaTarifa;

    /**
     * Gets the value of the cdEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdEmpresa() {
        return cdEmpresa;
    }

    /**
     * Sets the value of the cdEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdEmpresa(Integer value) {
        this.cdEmpresa = value;
    }

    /**
     * Gets the value of the cdTipoSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoSeguro() {
        return cdTipoSeguro;
    }

    /**
     * Sets the value of the cdTipoSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoSeguro(Integer value) {
        this.cdTipoSeguro = value;
    }

    /**
     * Gets the value of the cdTipoVeiculo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCdTipoVeiculo() {
        return cdTipoVeiculo;
    }

    /**
     * Sets the value of the cdTipoVeiculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCdTipoVeiculo(Integer value) {
        this.cdTipoVeiculo = value;
    }

    /**
     * Gets the value of the dtInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInicioVigencia() {
        return dtInicioVigencia;
    }

    /**
     * Sets the value of the dtInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInicioVigencia(String value) {
        this.dtInicioVigencia = value;
    }

    /**
     * Gets the value of the flNovaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlNovaTarifa() {
        return flNovaTarifa;
    }

    /**
     * Sets the value of the flNovaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlNovaTarifa(String value) {
        this.flNovaTarifa = value;
    }

}
