delete from acompanhamento;
delete from indenizacoes;
delete from terceiro_envolvido;
delete from proposta_comissao;
delete from proposta_endereco;
delete from resposta_perfil;
delete from sinistro_anexo;
delete from sinistro;
delete from condutor;
delete from automovel_cobertura;
delete from automovel_servicos;
delete from automovel;
delete from repasse_comissao;
delete from comissionado_proposta;
delete from imovel_cobertura;
delete from imovel_servicos;
delete from imovel;
delete from segurado_coberturas;
delete from beneficiario_empresarial;
delete from segurado_empresarial;
delete from seg_individual_coberturas;
delete from beneficiario_individual;
delete from beneficiario_empresarial;
delete from segurado_individual;
delete from risco_coberturas;
delete from risco_diversos;
delete from bordero_lancamento;
delete from bordero_comissao;
delete from repasse_comissao;
delete from lancamento_bonus;
delete from impostos;
delete from orcamento_bancos;
delete from orcamento_cobertura;
delete from orcamento_cobertura_iseg;
delete from orcamento_franquias;
delete from orcamento_seguradora;
delete from orcamento_seguro;
delete from orcamento_servicos;
delete from orcamento_servicos_iseg;
delete from parcelas_proposta;
delete from resposta_pos_venda;
delete from pendencia_pos_venda;
delete from pos_venda;
delete from proposta_endereco;
delete from resposta_perfil;
delete from proposta_comissao;
delete from repasse_comissao;
delete from comissionado_proposta;
delete from protocolo_itens;
delete from comissionado_agenciamento;
delete from parcelas_agenciamento;
delete from agenciamento;
delete from protocolo;
delete from transporte_coberturas;
delete from risco_transportes;
delete from automovel_cobertura;
delete from automovel_servicos;
delete from automovel;
delete from proposta_endereco;
delete from proposta_anexo;
delete from proposta_comissao;
delete from proposta_bancos;
delete from proposta;


delete from endereco where pessoa_id not in (select case when id is null then -1 else id end from seguradora) and pessoa_id not in (select case when id is null then -1 else id end from corretora) and pessoa_id not in (select case when id is null then -1 else id end from oficina) and pessoa_id not in (select case when id is null then -1 else id end from vistoriadora);
update pessoa set grupo_de_venda_id=null;
delete from grupo_produtor;
delete from grupo_de_venda;
delete from operadores_pos_venda;
delete from leitores_pos_venda;
delete from sms_creditos;
delete from sms_telefones_produtor;
delete from sms_eventos_corretora;
delete from sms_eventos_cliente;
delete from sms_eventos;
delete from produtor;
delete from dependentes;
delete from conta_corrente;
delete from pessoa_fisica where id not in (select case when pessoa_id is null then -1 else pessoa_id end from corretora);
delete from pessoa where (length(cpf_ou_cnpj)<=11 or cpf_ou_cnpj is null) and id not in (select case when pessoa_id is null then -1 else pessoa_id end from corretora) and id not in (select id from pessoa_juridica);
delete from pessoa_juridica where id not in (select case when id is null then -1 else id end from seguradora) and id not in (select case when id is null then -1 else id end from corretora) and id not in (select case when id is null then -1 else id end from oficina) and id not in (select case when id is null then -1 else id end from vistoriadora);
delete from pessoa where length(cpf_ou_cnpj)>11 and id not in (select case when id is null then -1 else id end from pessoa_juridica);
update corretora set pessoa_id = null;

delete from pendencia_pos_venda;
delete from resposta_pos_venda;
delete from pos_venda;
delete from usuario where corretora_id > 1;
delete from usuario where nome_Login <> 'ADMIN';
update pessoa set corretora_id=null;
delete from coberturas where corretora_id > 1;
delete from servicos where corretora_id > 1;
delete from questionario_pos_venda where corretora_id > 1;
delete from vistoriadora;
delete from corretora where id > 1;

