<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="s" uri="/struts-tags"%>

	<td width="2%" ><a href="#" onClick="document.getElementById('btnf3').click()" class="Main_ToolBar_Button" onMouseOver="window.status='Novo Registro';return true;" onMouseOut="window.status='';return true;" onblur="this.hideFocus=false" id="linkButtonNew"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_New" src="<s:url value="/common/web/images/blank.gif" />" title="Novo Registro" border="0" id="buttonNew"></a></td>
	<td class="Main_ToolBar_Separator_cell" ><img src="<s:url value="/common/web/images/blank.gif" />" class="Main_ToolBar_Separator"></td>
	<td width="2%" ><a href="#" onClick="submitForm(document.formEdit, '<s:url action="salvarLista.action" includeParams="none" />', true);" class="Main_ToolBar_Button" onblur="this.hideFocus=false" id="linkButtonSave_Relation"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Save_Relation" src="<s:url value="/common/web/images/blank.gif" />" title="Salva e volta para lista" border="0" id="buttonSave_Relation"></a></td>
	<td width="2%" ><a href="#" onClick="document.getElementById('btnf4').click()" class="Main_ToolBar_Button" onblur="this.hideFocus=false" id="linkButtonSave_New"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Save_New" src="<s:url value="/common/web/images/blank.gif" />" title="Salva e abre nova inclusão" border="0" id="buttonSave_New"></a></td>
	<td width="2%" ><a href="#" onClick="submitForm(document.formEdit, '<s:url action="salvarEditar.action" includeParams="none" />', true);" class="Main_ToolBar_Button" onblur="this.hideFocus=false" id="linkButtonSave"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Save" src="<s:url value="/common/web/images/blank.gif" />" title="Salva e edita" border="0" id="buttonSave"></a></td>
	<td class="Main_ToolBar_Separator_cell" ><img src="<s:url value="/common/web/images/blank.gif" />" class="Main_ToolBar_Separator"></td>
	<td width="2%" ><a href="#" class="Main_ToolBar_Button" onclick="document.formEdit.reset();this.hideFocus=true;" onblur="this.hideFocus=false" id="linkButtonUndo"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Undo" src="<s:url value="/common/web/images/blank.gif" />" title="Undo" border="0" id="buttonUndo"></a></td>
	<td class="Main_ToolBar_Separator_cell" ><img src="<s:url value="/common/web/images/blank.gif" />" class="Main_ToolBar_Separator"></td>
	<td width="2%" ><a href="#" class="Main_ToolBar_Button" onMouseOver="window.status='Primeira Página';return true;" onMouseOut="window.status='';return true;" onclick="this.hideFocus=true" onblur="this.hideFocus=false" id="linkButtonFirst"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_First" src="<s:url value="/common/web/images/blank.gif" />" title="Primeira Página" border="0" id="buttonFirst"></a></td>
	<td width="2%" ><a href="#" class="Main_ToolBar_Button" onMouseOver="window.status='Página Anterior';return true;" onMouseOut="window.status='';return true;" onclick="this.hideFocus=true" onblur="this.hideFocus=false" id="linkButtonPrevious"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Previous" src="<s:url value="/common/web/images/blank.gif" />" title="Página Anterior" border="0" id="buttonPrevious"></a></td>
	<td width="2%" ><a href="#" class="Main_ToolBar_Button" onMouseOver="window.status='Próxima Página';return true;" onMouseOut="window.status='';return true;" onclick="this.hideFocus=true" onblur="this.hideFocus=false" id="linkButtonNext"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Next" src="<s:url value="/common/web/images/blank.gif" />" title="Próxima Página" border="0" id="buttonNext"></a></td>
	<td width="2%" ><a href="#" class="Main_ToolBar_Button" onMouseOver="window.status='Última Página';return true;" onMouseOut="window.status='';return true;" onclick="this.hideFocus=true" onblur="this.hideFocus=false" id="linkButtonLast"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_Last" src="<s:url value="/common/web/images/blank.gif" />" title="Último Página" border="0" id="buttonLast"></a></td>
	<td class="Main_ToolBar_Separator_cell" ><img src="<s:url value="/common/web/images/blank.gif" />" class="Main_ToolBar_Separator"></td>
	<td class="Main_ToolBar_Space"></td>
	<!--  
	<td width="1"><img src="<s:url value="/common/web/images/blank.gif" />" class="Main_ToolBar_textlabel_bg_left" border="0"></td>
	<td class="Main_ToolBar_textlabel_bg_body"><a class="Main_ToolBar_text_relatedinfo" href="#" onclick="">Linked Items</a></td>
	<td class="Main_ToolBar_textlabel_bg_right" width="2%" ><a href="#" onClick="" class="Main_ToolBar_Button" onMouseOver="window.status='Linked Items';return true;" onMouseOut="window.status='';return true;" onclick="this.hideFocus=true" onblur="this.hideFocus=false" id="linkButtonRelatedInfo"><img class="Main_ToolBar_Button_Icon Main_ToolBar_Button_Icon_RelatedInfo" src="<s:url value="/common/web/images/blank.gif" />" title="Linked Items" border="0" id="buttonRelatedInfo"></a></td>
	-->