wine C:\\JSMin\\jsmin <./common/common.js>./common/common-pack.js
wine C:\\JSMin\\jsmin <./common/confirm.js>./common/confirm-pack.js
wine C:\\JSMin\\jsmin <./common/displayList.js>./common/displayList-pack.js
wine C:\\JSMin\\jsmin <./common/event.js>./common/event-pack.js
wine C:\\JSMin\\jsmin <./common/formatCurrency.js>./common/formatCurrency-pack.js
wine C:\\JSMin\\jsmin <./common/geral.js>./common/geral-pack.js
wine C:\\JSMin\\jsmin <./common/hotkeys.js>./common/hotkeys-pack.js
wine C:\\JSMin\\jsmin <./common/is-date.js>./common/is-date-pack.js
wine C:\\JSMin\\jsmin <./common/jquery-form.js>./common/jquery-form-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.bgiframe.js>./common/jquery.bgiframe-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.meiomask.js>./common/jquery.meiomask-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.dimensions.js>./common/jquery.dimensions-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.simplemodal-1.1.1.js>./common/jquery.simplemodal-1.1.1-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.tooltip.js>./common/jquery.tooltip-pack.js
wine C:\\JSMin\\jsmin <./common/masked-input.js>./common/masked-input-pack.js
wine C:\\JSMin\\jsmin <./js/propostaImoveis/script.js>./js/propostaImoveis/script-pack.js
wine C:\\JSMin\\jsmin <./js/propostaImoveis/tab-panel.js>./js/propostaImoveis/tab-panel-pack.js
wine C:\\JSMin\\jsmin <./js/propostaVidaIndividual/script.js>./js/propostaVidaIndividual/script-pack.js
wine C:\\JSMin\\jsmin <./js/propostaVidaIndividual/tab-panel.js>./js/propostaVidaIndividual/tab-panel-pack.js
wine C:\\JSMin\\jsmin <./js/propostaVidaEmpresarial/script.js>./js/propostaVidaEmpresarial/script-pack.js
wine C:\\JSMin\\jsmin <./js/propostaVidaEmpresarial/tab-panel.js>./js/propostaVidaEmpresarial/tab-panel-pack.js
wine C:\\JSMin\\jsmin <./js/wizard/script.js>./js/wizard/script-pack.js
wine C:\\JSMin\\jsmin <./common/wizardFinal/tab-panel.js>./common/wizardFinal/tab-panel-pack.js
wine C:\\JSMin\\jsmin <./common/TableSort.js>./common/TableSort-pack.js
wine C:\\JSMin\\jsmin <./common/ui.core.js>./common/ui.core-pack.js
wine C:\\JSMin\\jsmin <./common/ui.accordion.js>./common/ui.accordion-pack.js
wine C:\\JSMin\\jsmin <./common/ui.datepicker.js>./common/ui.datepicker-pack.js
wine C:\\JSMin\\jsmin <./common/xbDebug.js>./common/xbDebug-pack.js
wine C:\\JSMin\\jsmin <./common/xbDOM.js>./common/xbDOM-pack.js
wine C:\\JSMin\\jsmin <./common/xbLibrary.js>./common/xbLibrary-pack.js
wine C:\\JSMin\\jsmin <./common/xbStyle-css.js>./common/xbStyle-css-pack.js
wine C:\\JSMin\\jsmin <./common/xbStyle.js>./common/xbStyle-pack.js
wine C:\\JSMin\\jsmin <./common/autocomplete.js>./common/autocomplete-pack.js
wine C:\\JSMin\\jsmin <./common/tabpane.js>./common/tabpane-pack.js
wine C:\\JSMin\\jsmin <./common/web/js/utils.js>./common/web/js/utils-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.form-new.js>./common/jquery.form-new-pack.js
wine C:\\JSMin\\jsmin <./common/jquery.autocomplete.js>./common/jquery.autocomplete-pack.js
wine C:\\JSMin\\jsmin <./common/jquery-1.3.2.js>./common/jquery-1.3.2-pack.js
wine C:\\JSMin\\jsmin <./js/propostaRiscosDiversos/tab-panel.js>./js/propostaRiscosDiversos/tab-panel-pack.js
wine C:\\JSMin\\jsmin <./js/propostaRiscosDiversos/tabpane.js>./js/propostaRiscosDiversos/tabpane-pack.js
wine C:\\JSMin\\jsmin <./js/propostaRiscosDiversos/script.js>./js/propostaRiscosDiversos/script-pack.js
wine C:\\JSMin\\jsmin <./js/propostaRiscosDiversos/hotkeys.js>./js/propostaRiscosDiversos/hotkeys-pack.js
