//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.subscricao.model.client.qar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusQuestionarioQarVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusQuestionarioQarVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codRetorno" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="mensagemRetorno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusCondutorQarVo" type="{http://qar.client.model.subscricao.paol.bradseg.com.br}StatusCondutorQarVo" minOccurs="0"/>
 *         &lt;element name="statusEspecieSeguro" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusIndicativoNovaTarifa" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusModalidadeSeguro" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusProprietarioQarVo" type="{http://qar.client.model.subscricao.paol.bradseg.com.br}StatusProprietarioQarVo" minOccurs="0"/>
 *         &lt;element name="statusSeguradoCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusSeguradoProprietario" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusSeguradoQarVo" type="{http://qar.client.model.subscricao.paol.bradseg.com.br}StatusSeguradoQarVo" minOccurs="0"/>
 *         &lt;element name="statusTipoPerfil" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusQuestionarioQarVo", namespace = "http://qar.client.model.subscricao.paol.bradseg.com.br", propOrder = {
    "codRetorno",
    "mensagemRetorno",
    "statusCondutorQarVo",
    "statusEspecieSeguro",
    "statusIndicativoNovaTarifa",
    "statusModalidadeSeguro",
    "statusProprietarioQarVo",
    "statusSeguradoCondutor",
    "statusSeguradoProprietario",
    "statusSeguradoQarVo",
    "statusTipoPerfil"
})
public class StatusQuestionarioQarVo {

    protected Long codRetorno;
    protected String mensagemRetorno;
    protected StatusCondutorQarVo statusCondutorQarVo;
    protected Long statusEspecieSeguro;
    protected Long statusIndicativoNovaTarifa;
    protected Long statusModalidadeSeguro;
    protected StatusProprietarioQarVo statusProprietarioQarVo;
    protected Long statusSeguradoCondutor;
    protected Long statusSeguradoProprietario;
    protected StatusSeguradoQarVo statusSeguradoQarVo;
    protected Long statusTipoPerfil;

    /**
     * Gets the value of the codRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCodRetorno() {
        return codRetorno;
    }

    /**
     * Sets the value of the codRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCodRetorno(Long value) {
        this.codRetorno = value;
    }

    /**
     * Gets the value of the mensagemRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensagemRetorno() {
        return mensagemRetorno;
    }

    /**
     * Sets the value of the mensagemRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensagemRetorno(String value) {
        this.mensagemRetorno = value;
    }

    /**
     * Gets the value of the statusCondutorQarVo property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCondutorQarVo }
     *     
     */
    public StatusCondutorQarVo getStatusCondutorQarVo() {
        return statusCondutorQarVo;
    }

    /**
     * Sets the value of the statusCondutorQarVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCondutorQarVo }
     *     
     */
    public void setStatusCondutorQarVo(StatusCondutorQarVo value) {
        this.statusCondutorQarVo = value;
    }

    /**
     * Gets the value of the statusEspecieSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusEspecieSeguro() {
        return statusEspecieSeguro;
    }

    /**
     * Sets the value of the statusEspecieSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusEspecieSeguro(Long value) {
        this.statusEspecieSeguro = value;
    }

    /**
     * Gets the value of the statusIndicativoNovaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusIndicativoNovaTarifa() {
        return statusIndicativoNovaTarifa;
    }

    /**
     * Sets the value of the statusIndicativoNovaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusIndicativoNovaTarifa(Long value) {
        this.statusIndicativoNovaTarifa = value;
    }

    /**
     * Gets the value of the statusModalidadeSeguro property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusModalidadeSeguro() {
        return statusModalidadeSeguro;
    }

    /**
     * Sets the value of the statusModalidadeSeguro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusModalidadeSeguro(Long value) {
        this.statusModalidadeSeguro = value;
    }

    /**
     * Gets the value of the statusProprietarioQarVo property.
     * 
     * @return
     *     possible object is
     *     {@link StatusProprietarioQarVo }
     *     
     */
    public StatusProprietarioQarVo getStatusProprietarioQarVo() {
        return statusProprietarioQarVo;
    }

    /**
     * Sets the value of the statusProprietarioQarVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusProprietarioQarVo }
     *     
     */
    public void setStatusProprietarioQarVo(StatusProprietarioQarVo value) {
        this.statusProprietarioQarVo = value;
    }

    /**
     * Gets the value of the statusSeguradoCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusSeguradoCondutor() {
        return statusSeguradoCondutor;
    }

    /**
     * Sets the value of the statusSeguradoCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusSeguradoCondutor(Long value) {
        this.statusSeguradoCondutor = value;
    }

    /**
     * Gets the value of the statusSeguradoProprietario property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusSeguradoProprietario() {
        return statusSeguradoProprietario;
    }

    /**
     * Sets the value of the statusSeguradoProprietario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusSeguradoProprietario(Long value) {
        this.statusSeguradoProprietario = value;
    }

    /**
     * Gets the value of the statusSeguradoQarVo property.
     * 
     * @return
     *     possible object is
     *     {@link StatusSeguradoQarVo }
     *     
     */
    public StatusSeguradoQarVo getStatusSeguradoQarVo() {
        return statusSeguradoQarVo;
    }

    /**
     * Sets the value of the statusSeguradoQarVo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusSeguradoQarVo }
     *     
     */
    public void setStatusSeguradoQarVo(StatusSeguradoQarVo value) {
        this.statusSeguradoQarVo = value;
    }

    /**
     * Gets the value of the statusTipoPerfil property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusTipoPerfil() {
        return statusTipoPerfil;
    }

    /**
     * Sets the value of the statusTipoPerfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusTipoPerfil(Long value) {
        this.statusTipoPerfil = value;
    }

}
