//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.subscricao.model.client.qar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusCondutorQarVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusCondutorQarVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusAtividadeCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusCepEstudo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusCepLocalTrabalho" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusCepPernoite" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusCondutorEntre18E25" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusCpfCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusDataNascimentoCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusEstadoCivilCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusGaragemLocalEstudo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusGaragemLocalTrabalho" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusGaragemPernoite" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusKmMediaMensal" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusLocalEstudoFixo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusLocalTrabalhoFixo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusRamoAtividadeCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusSexoCondutor" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusUsoVeiculo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusUtilizacaoEstudo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusUtilizacaoTrabalho" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusCondutorQarVo", namespace = "http://qar.client.model.subscricao.paol.bradseg.com.br", propOrder = {
    "statusAtividadeCondutor",
    "statusCepEstudo",
    "statusCepLocalTrabalho",
    "statusCepPernoite",
    "statusCondutorEntre18E25",
    "statusCpfCondutor",
    "statusDataNascimentoCondutor",
    "statusEstadoCivilCondutor",
    "statusGaragemLocalEstudo",
    "statusGaragemLocalTrabalho",
    "statusGaragemPernoite",
    "statusKmMediaMensal",
    "statusLocalEstudoFixo",
    "statusLocalTrabalhoFixo",
    "statusRamoAtividadeCondutor",
    "statusSexoCondutor",
    "statusUsoVeiculo",
    "statusUtilizacaoEstudo",
    "statusUtilizacaoTrabalho"
})
public class StatusCondutorQarVo {

    protected Long statusAtividadeCondutor;
    protected Long statusCepEstudo;
    protected Long statusCepLocalTrabalho;
    protected Long statusCepPernoite;
    protected Long statusCondutorEntre18E25;
    protected Long statusCpfCondutor;
    protected Long statusDataNascimentoCondutor;
    protected Long statusEstadoCivilCondutor;
    protected Long statusGaragemLocalEstudo;
    protected Long statusGaragemLocalTrabalho;
    protected Long statusGaragemPernoite;
    protected Long statusKmMediaMensal;
    protected Long statusLocalEstudoFixo;
    protected Long statusLocalTrabalhoFixo;
    protected Long statusRamoAtividadeCondutor;
    protected Long statusSexoCondutor;
    protected Long statusUsoVeiculo;
    protected Long statusUtilizacaoEstudo;
    protected Long statusUtilizacaoTrabalho;

    /**
     * Gets the value of the statusAtividadeCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusAtividadeCondutor() {
        return statusAtividadeCondutor;
    }

    /**
     * Sets the value of the statusAtividadeCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusAtividadeCondutor(Long value) {
        this.statusAtividadeCondutor = value;
    }

    /**
     * Gets the value of the statusCepEstudo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCepEstudo() {
        return statusCepEstudo;
    }

    /**
     * Sets the value of the statusCepEstudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCepEstudo(Long value) {
        this.statusCepEstudo = value;
    }

    /**
     * Gets the value of the statusCepLocalTrabalho property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCepLocalTrabalho() {
        return statusCepLocalTrabalho;
    }

    /**
     * Sets the value of the statusCepLocalTrabalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCepLocalTrabalho(Long value) {
        this.statusCepLocalTrabalho = value;
    }

    /**
     * Gets the value of the statusCepPernoite property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCepPernoite() {
        return statusCepPernoite;
    }

    /**
     * Sets the value of the statusCepPernoite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCepPernoite(Long value) {
        this.statusCepPernoite = value;
    }

    /**
     * Gets the value of the statusCondutorEntre18E25 property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCondutorEntre18E25() {
        return statusCondutorEntre18E25;
    }

    /**
     * Sets the value of the statusCondutorEntre18E25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCondutorEntre18E25(Long value) {
        this.statusCondutorEntre18E25 = value;
    }

    /**
     * Gets the value of the statusCpfCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCpfCondutor() {
        return statusCpfCondutor;
    }

    /**
     * Sets the value of the statusCpfCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCpfCondutor(Long value) {
        this.statusCpfCondutor = value;
    }

    /**
     * Gets the value of the statusDataNascimentoCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusDataNascimentoCondutor() {
        return statusDataNascimentoCondutor;
    }

    /**
     * Sets the value of the statusDataNascimentoCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusDataNascimentoCondutor(Long value) {
        this.statusDataNascimentoCondutor = value;
    }

    /**
     * Gets the value of the statusEstadoCivilCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusEstadoCivilCondutor() {
        return statusEstadoCivilCondutor;
    }

    /**
     * Sets the value of the statusEstadoCivilCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusEstadoCivilCondutor(Long value) {
        this.statusEstadoCivilCondutor = value;
    }

    /**
     * Gets the value of the statusGaragemLocalEstudo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusGaragemLocalEstudo() {
        return statusGaragemLocalEstudo;
    }

    /**
     * Sets the value of the statusGaragemLocalEstudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusGaragemLocalEstudo(Long value) {
        this.statusGaragemLocalEstudo = value;
    }

    /**
     * Gets the value of the statusGaragemLocalTrabalho property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusGaragemLocalTrabalho() {
        return statusGaragemLocalTrabalho;
    }

    /**
     * Sets the value of the statusGaragemLocalTrabalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusGaragemLocalTrabalho(Long value) {
        this.statusGaragemLocalTrabalho = value;
    }

    /**
     * Gets the value of the statusGaragemPernoite property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusGaragemPernoite() {
        return statusGaragemPernoite;
    }

    /**
     * Sets the value of the statusGaragemPernoite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusGaragemPernoite(Long value) {
        this.statusGaragemPernoite = value;
    }

    /**
     * Gets the value of the statusKmMediaMensal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusKmMediaMensal() {
        return statusKmMediaMensal;
    }

    /**
     * Sets the value of the statusKmMediaMensal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusKmMediaMensal(Long value) {
        this.statusKmMediaMensal = value;
    }

    /**
     * Gets the value of the statusLocalEstudoFixo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusLocalEstudoFixo() {
        return statusLocalEstudoFixo;
    }

    /**
     * Sets the value of the statusLocalEstudoFixo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusLocalEstudoFixo(Long value) {
        this.statusLocalEstudoFixo = value;
    }

    /**
     * Gets the value of the statusLocalTrabalhoFixo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusLocalTrabalhoFixo() {
        return statusLocalTrabalhoFixo;
    }

    /**
     * Sets the value of the statusLocalTrabalhoFixo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusLocalTrabalhoFixo(Long value) {
        this.statusLocalTrabalhoFixo = value;
    }

    /**
     * Gets the value of the statusRamoAtividadeCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusRamoAtividadeCondutor() {
        return statusRamoAtividadeCondutor;
    }

    /**
     * Sets the value of the statusRamoAtividadeCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusRamoAtividadeCondutor(Long value) {
        this.statusRamoAtividadeCondutor = value;
    }

    /**
     * Gets the value of the statusSexoCondutor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusSexoCondutor() {
        return statusSexoCondutor;
    }

    /**
     * Sets the value of the statusSexoCondutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusSexoCondutor(Long value) {
        this.statusSexoCondutor = value;
    }

    /**
     * Gets the value of the statusUsoVeiculo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusUsoVeiculo() {
        return statusUsoVeiculo;
    }

    /**
     * Sets the value of the statusUsoVeiculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusUsoVeiculo(Long value) {
        this.statusUsoVeiculo = value;
    }

    /**
     * Gets the value of the statusUtilizacaoEstudo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusUtilizacaoEstudo() {
        return statusUtilizacaoEstudo;
    }

    /**
     * Sets the value of the statusUtilizacaoEstudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusUtilizacaoEstudo(Long value) {
        this.statusUtilizacaoEstudo = value;
    }

    /**
     * Gets the value of the statusUtilizacaoTrabalho property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusUtilizacaoTrabalho() {
        return statusUtilizacaoTrabalho;
    }

    /**
     * Sets the value of the statusUtilizacaoTrabalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusUtilizacaoTrabalho(Long value) {
        this.statusUtilizacaoTrabalho = value;
    }

}
