//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.com.bradseg.paol.subscricao.model.client.qar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusSeguradoQarVo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusSeguradoQarVo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusCpfCnpjSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusDataNascimentoSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusEstadoCivilSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusNomeSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusSexoSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="statusTipoSegurado" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusSeguradoQarVo", namespace = "http://qar.client.model.subscricao.paol.bradseg.com.br", propOrder = {
    "statusCpfCnpjSegurado",
    "statusDataNascimentoSegurado",
    "statusEstadoCivilSegurado",
    "statusNomeSegurado",
    "statusSexoSegurado",
    "statusTipoSegurado"
})
public class StatusSeguradoQarVo {

    protected Long statusCpfCnpjSegurado;
    protected Long statusDataNascimentoSegurado;
    protected Long statusEstadoCivilSegurado;
    protected Long statusNomeSegurado;
    protected Long statusSexoSegurado;
    protected Long statusTipoSegurado;

    /**
     * Gets the value of the statusCpfCnpjSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusCpfCnpjSegurado() {
        return statusCpfCnpjSegurado;
    }

    /**
     * Sets the value of the statusCpfCnpjSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusCpfCnpjSegurado(Long value) {
        this.statusCpfCnpjSegurado = value;
    }

    /**
     * Gets the value of the statusDataNascimentoSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusDataNascimentoSegurado() {
        return statusDataNascimentoSegurado;
    }

    /**
     * Sets the value of the statusDataNascimentoSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusDataNascimentoSegurado(Long value) {
        this.statusDataNascimentoSegurado = value;
    }

    /**
     * Gets the value of the statusEstadoCivilSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusEstadoCivilSegurado() {
        return statusEstadoCivilSegurado;
    }

    /**
     * Sets the value of the statusEstadoCivilSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusEstadoCivilSegurado(Long value) {
        this.statusEstadoCivilSegurado = value;
    }

    /**
     * Gets the value of the statusNomeSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusNomeSegurado() {
        return statusNomeSegurado;
    }

    /**
     * Sets the value of the statusNomeSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusNomeSegurado(Long value) {
        this.statusNomeSegurado = value;
    }

    /**
     * Gets the value of the statusSexoSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusSexoSegurado() {
        return statusSexoSegurado;
    }

    /**
     * Sets the value of the statusSexoSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusSexoSegurado(Long value) {
        this.statusSexoSegurado = value;
    }

    /**
     * Gets the value of the statusTipoSegurado property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusTipoSegurado() {
        return statusTipoSegurado;
    }

    /**
     * Sets the value of the statusTipoSegurado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusTipoSegurado(Long value) {
        this.statusTipoSegurado = value;
    }

}
